### ISSUE TITLE
Adaptation des niveaux par rapport a ceux du personnage non fonctionnel (prod)

### ISSUE THREAD

**Issue by EnekoCazenave** [Supamiu/ffxiv-teamcraft#11]
Lorsque je me connecte avec mon personnage et que je click sur "adapt to character", rien ne se passe 
Errors dans le log : 

- "ERROR TypeError: Cannot read property 'classjobs' of undefined"
- "Error: permission_denied at /users/pft0pxNd9Kdpf7rxoRD4OyjT7Bx2/lists/-KssVFhcl6IEhlOwYk6m: Client doesn't have permission to access the desired data."

**Comment by Supamiu** [comment]
Es-tu identifié sur le site? 

J'ai corrigé un bug récemment qui te rendait non-connecté par défaut, même pas en anonyme, ce qui a créé un petit soucis. C'est réglé depuis environ 1h normalement.

Je vérifie les droits et la feature de mon coté pour voir si j'arrive à reproduire le bug.

**Comment by EnekoCazenave** [comment]
Quand je re-ouvre le site, je suis pas connecté, mais je ne suis pas en Anonyme non plus, il y a toujours le nom de mon personnage, mais pas son image.

**Comment by Supamiu** [comment]
Ok j'ai réussi à reproduire le bug, il sera fixé d'ici très peu de temps :smile:

**Comment by Supamiu** [comment]
Le soucis vient d'un changement de structure de données de la part de xivsync, aucune annonce n'a été faite à ce sujet. Si tu n'avais pas report le bug, il aurait pu traîner longtemps...

**Comment by EnekoCazenave** [comment]
Be vu que j'ai ce problème d'installation d'environnement, je vais faire des tests pour t'aider au mieux ;)

**Comment by Supamiu** [comment]
C'est réglé ^^ je met juste en place un autre fix pour l'authentification et je met le tout en prod.

**Comment by Supamiu** [comment]
C'est réglé et en prod, essaye juste de signaler en anglais pur la prochaine fois :wink:
