### ISSUE TITLE
feat: add list merging

### ISSUE THREAD

**Issue by AltanRapsied** [Supamiu/ffxiv-teamcraft#116]

**Comment by Supamiu** [comment]
We need some help to define the User story behind this, aka how it has to be done on UI side, as the logic part is already done.

**Comment by AltanRapsied** [comment]
First you create lists, or clone them from public lists, or both.
Then on our list page, you can click on the "merge list" button on top of the page. This will prompt a pop-up asking you to cross the lists you want to merge together, and ask a name for the new list created.
The new list is then created while those used to create it are deleted. (I believe they don't need the previous lists anymore since they merged it to do all of them at the same time).

**Comment by Supamiu** [comment]
The only implementation needed is UI/UX one, as `List` already has a `merge` method, merging two lists together. See https://github.com/Supamiu/ffxiv-teamcraft/blob/master/src/app/model/list/list.ts#L102-L119
