### ISSUE TITLE
feat:  ability to create a 'friends list' with the intent that you can see who can craft/provide items at a glance

### ISSUE THREAD

**Issue by DJCecil2** [Supamiu/ffxiv-teamcraft#13]
From: https://www.reddit.com/r/ffxiv/comments/6yfyg0/ffxiv_teamcraft_first_release/dmn3taw/?context=10000

As a logged in user I would like the ability to see which of my crafter/gatherer friends would be able to make/gather an item for me.

**Comment by Supamiu** [comment]
I just found this on https://github.com/xivdb/api: https://api.xivdb.com/character/730968?data=gearsets

It can be useful to keep tracking on user stats, but it doesn't show which masterbooks are unlocked tho.

**Comment by Supamiu** [comment]
Closing it for now, could be considered later on but will require a lot of discussion with users in order to get the best UX for that.
