### ISSUE TITLE
feat: multi-user list edition

### ISSUE THREAD

**Issue by AltanRapsied** [Supamiu/ffxiv-teamcraft#134]
- Click on the share button on the right of a list's title.
- A prompt shows up, asking you to enter the mails of the people you want to share your list with.
- If the mail is correct, the concerned person will receive a mail noticing them that you shared your list with them.
- The person with whom you shared your list with will have it appear on their list page with a "shared" icon instead of the "share" button.
- When entering a list, the people who have access to the list other than you will be displayed on top of the list.
- If you're the creator of the list, you can click on "remove permission" on top of the list. This will open a prompt with the list of the characters of the people you shared your list with. Cross those you want to remove the share with and save.

**Comment by Supamiu** [comment]
related to #277
