### ISSUE TITLE
List page hiding buttons when width is reduced

### ISSUE THREAD

**Issue by tdewey7** [Supamiu/ffxiv-teamcraft#137]
Here is a screenshot in which all of the buttons for the functions of the Lists are hidden except for half of the 'Share' button. This makes opening the list from this page impossible without resizing the page to reveal the buttons. The issue seems to arise at a page width of <800 pixels. 

![image](https://user-images.githubusercontent.com/20916345/33791490-48e20672-dc5a-11e7-9bff-e1d4f9bf1c60.png)

**Comment by Supamiu** [comment]
Seems like this issue is coming from the fact that list description has a min-width which is pretty high, so the buttons are going away to leave space for the description.

Going to be fixed for 3.1 for sure.

By the way, thank you for your public lists, they are quite useful 😄
