### ISSUE TITLE
feat: forbid temporary list to be public list

### ISSUE THREAD

**Issue by AltanRapsied** [Supamiu/ffxiv-teamcraft#138]

**Comment by Supamiu** [comment]
In `list-details.component.html`, simply add `&& !list.ephemeral` to the public list button's `*ngIf`

**Comment by Supamiu** [comment]
Seems like it was already done. Please open a new issue if you see another ephemeral list in public lists, with a screenshot to make sure it's an ephemeral list, not a display bug.
