### ISSUE TITLE
Configurable Recipe Links

### ISSUE THREAD

**Issue by aluink** [Supamiu/ffxiv-teamcraft#14]
I distain xivdb.com and because of that, I love the feature on ariyala that allows you to choose where the item links take you.  I'm sure I'm not the only one who feels this way.

![ariyala](https://user-images.githubusercontent.com/25197/30132504-8aa2d526-931e-11e7-8c99-6e2ff9b0a97f.JPG)

**Comment by Supamiu** [comment]
If we can find a proper way to include this with good UX, it would be a really nice feature to have.
