### ISSUE TITLE
Bug: Crafts requiring equipment as materials show equipment in the wrong tier.

### ISSUE THREAD

**Issue by YeahButHats** [Supamiu/ffxiv-teamcraft#143]
I made this list for a gear upgrade: https://ffxivteamcraft.com/list/-L02ghB7e6yCAJ0YS6eC and I noticed that the Mythril Elmo shows in Tier 1 despite requiring items from the Tier 2 craft. I would expect it to be put on a Tier 3 craft list.

Then, trying to get a simpler example, I noticed that this list https://ffxivteamcraft.com/list/-L02vKC36YijAHsLdUzC shows the Mythril Elmo in Tier 2, but the Plates and Rivets in Tier 1. I would expect the Plates and Rivets to be in Tier 2, and the Mythril Elmo to be on Tier 3, as mentioned above.

Regardless of expectations, this behavior is inconsistent across lists.

**Comment by Supamiu** [comment]
Hello @YeahButHats , thank you for your report.

Regenerating the list seems to fix the first issue you mentioned, that being said, the second one isn't fixed, I cloned your list so I can work on it easily.

This will be fixed for 3.1.

**Comment by Supamiu** [comment]
Fixed, will be in the next version (3.1)
