### ISSUE TITLE
style: show amount of items required to reach total when hovering the input field

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#145]
The idea is to add a `matTooltip`, translated, that shows something like "XX to reach total" when hovering the input field.

Will require a bit of translation, so the displayed string will have to be translated.

**Comment by Supamiu** [comment]
Tooltip documentation: https://material.angular.io/components/tooltip/overview

**Comment by noemi-salaun** [comment]
On which input on which page do you wan't to add the tooltip ?

What do you mean by _"items required to reach total"_ ?

If the input says 5/12, the tooltip should say _"7 to reach total"_ ?

**Comment by Supamiu** [comment]
The tooltip will be placed in the `AmountInput `component (https://github.com/Supamiu/ffxiv-teamcraft/tree/master/src/app/modules/common-components/amount-input), with a boolean used for configuration, default to false, used to provide, or not, a tooltip using mat-tooltip directive.

*items required to reach total* means that if you have, for instance, 348 iron ore and you need a total of 457, the amount of items to reach total is 109. I used big numbers to point the fact that it's needed, because teamcraft is here to do the maths, so you just have to do the ingame part 😄
