### ISSUE TITLE
bug: list doesn't update automatically in "Area Breakdown" view

### ISSUE THREAD

**Issue by Zelly** [Supamiu/ffxiv-teamcraft#148]
Was doing a list with the FC we were both in the "Area Breakdown" view, and were checking off things, however they wouldn't show up checked on other peoples lists unless we refreshed page.

**Comment by Supamiu** [comment]
Hi, thank you for reporting this issue, I'll check this asap, if I fix it, it'll be in production for sure, as this is a quite critical issue.

Also, is it working fine without area breakdown?

**Comment by Supamiu** [comment]
The fix will be in production once this issue is closed, thank you again for your report, this bug was a pretty critical one.
