### ISSUE TITLE
XIVDB Links Broken

### ISSUE THREAD

**Issue by aluink** [Supamiu/ffxiv-teamcraft#15]
It appears the links to recipes/items are broken to XIVDB.

For example, upon clicking on Holy Rainbow Work Gloves,  I am taken to http://xivdb.com/recipe/2749 which appears to be an incomplete URL.  The complete URL is http://xivdb.com/item/11994/holy+rainbow+work+gloves.

**Comment by Supamiu** [comment]
The main issue with that is the fact that links have to work in every language, that's why I didn't add the item name in the link.

That being said, the link appears to be really broken if the name is not in it, I'll look for a solution to that tomorrow.

**Comment by aluink** [comment]
It appears the name can be in English regardless of the language.

http://xivdb.com/item/12589/holy+rainbow+cloth
http://fr.xivdb.com/item/12589/holy+rainbow+cloth
http://de.xivdb.com/item/12589/holy+rainbow+cloth

**Comment by aluink** [comment]
It appears the name can be in English regardless of the language.  If you're cool with the links taking you to the item instead of the recipe, then I have a fix for you :).

http://xivdb.com/item/12589/holy+rainbow+cloth
http://fr.xivdb.com/item/12589/holy+rainbow+cloth
http://de.xivdb.com/item/12589/holy+rainbow+cloth
http://ja.xivdb.com/item/12589/holy+rainbow+cloth

**Comment by Supamiu** [comment]
I'm totally cool with that, wondering if it's not the best solution tbh ^^.

If you've done a fix and want to merge it, feel free to create the first external PR of the repo 😃

**Comment by aluink** [comment]
Links in the crafting list are broken.  I'm assuming it's related to this change.  Should reopen this issue till it's resolved.

**Comment by Supamiu** [comment]
The links are broken in english version of the site in the list view only.

That's because the logic used for these links is not the same as the one used for recipe links, that's a bad code design issue ^^.

I'll fix this in the refactoring process :+1:
