### ISSUE TITLE
bug: stuck on "Character information" popup

### ISSUE THREAD

**Issue by noemi-salaun** [Supamiu/ffxiv-teamcraft#150]
First time on the site.

Signin with facebook.

Then without asking, it tells me that my character isn't found, but I never give my character name or whatever.

And then, I'm stuck on the home page with this popup opened. Even when reloading the page.

**Comment by noemi-salaun** [comment]
I understand the site can't work without my char info, but I cannot even logout when this popup is shown.

**Comment by Supamiu** [comment]
The only way to log out is to clear the localstorage.

It's made like that because when you have an account created & logged in, we assume that you have a character, so you can't use the website without it, sicne some features would crash and this is not handled at the moment.

**Comment by noemi-salaun** [comment]
So maybe just add a logout button in this popup, so you don't have to manually clear the local storage

**Comment by Supamiu** [comment]
Indeed, could be a nice thing to improve the UX of this popup.
