### ISSUE TITLE
bug: recipe tooltip pops behind the top bar when too big

### ISSUE THREAD

**Issue by noemi-salaun** [Supamiu/ffxiv-teamcraft#152]
Recipes tooltips pop behind the top bar when the tooltip is too big.

![screenshot](https://user-images.githubusercontent.com/2726492/34364639-fe4f996c-ea87-11e7-9778-b9fa98bd30c3.jpg)

**Comment by Supamiu** [comment]
This will be a quite hard one to fix (see https://github.com/Supamiu/ffxiv-teamcraft/tree/master/src/app/modules/tooltip for code references). 

The issue is that the tooltip is placed with absolute positionning, so I don't have a solution to this right now. If you have one, feel free to make a PR 👍

**Comment by noemi-salaun** [comment]
It could be done by using a smarter positionning, or injecting the dom element in a higher parent in the dom. A parent that can be in front of everything.
You can look at the Material Dialog (I don't know if the Material Tooltip use this).
I will look into the Angular CDK, it's the base services used to build complexe component behavior.

**Comment by Supamiu** [comment]
The main issue is proper positioning, at the moment the tooltip component is used as a container, with an id provided. so when you hover the container, you see the tooltip. Could be fixed using a better z-index maybe, to make it shown on top of the topbar.

**Comment by noemi-salaun** [comment]
The problem does not came from the tooltip displayed behind the top bar. The probleme comes from every containers set on `overflow: auto`. The tooltip cannot be displayed outside of it's parent. In our case the `mat-sidenav-content` and the `.content` inside it.
