### ISSUE TITLE
bug: responsive design doesn't trigger changes detection

### ISSUE THREAD

**Issue by noemi-salaun** [Supamiu/ffxiv-teamcraft#153]
On the recipes page, when I resize my window, each row stay in a single line. But when I click on something, or just hover a button with a Material tooltip, the responsive design kicks in and set the content on two lines. Same thing when widening the window.

![ezgif-3-f4fc7a6de2](https://user-images.githubusercontent.com/2726492/34364941-3daf5bd0-ea8b-11e7-9b71-45c2a620500a.gif)

It looks like the window resizing does not trigger the change detection

**Comment by Supamiu** [comment]
I wonder if placing a change detection call in `AppComponent `during media change detection would be enough, as the issue clearly comes from elements with an `OnPush `change detection strategy.

**Comment by noemi-salaun** [comment]
Which library do you use to handle responsive design ?
For OnPush component, you have to `markForCheck()` in the component ˋChangeDetectorRef`.

**Comment by Supamiu** [comment]
I'm using @angular/flex-layout, they provide a `MediaObservable` which emits a new value each time the display changes. The idea is to connect on this observable to trigger change detector by marking root component for changes. But if it's not "enough" to mark `OnPush `components for change, then it might become a bit boring, as the component will have to inherit a specific class implementing this feature.
