### ISSUE TITLE
Bug: Multi-stage fc crafts show as ready-to-build too early

### ISSUE THREAD

**Issue by Riven5** [Supamiu/ffxiv-teamcraft#166]
This only happens to crafts which use the same mat on multiple stages.

For example, Invincible II-type Aftcastle needs 12 Darksteel Ingots on stage 2, and 18 more on stage 3, but as soon as you have 18 it gets marked as craftable, rather than waiting for the full 30.

**Comment by Supamiu** [comment]
Hi, thank you for your bug report.

I'll investigate this as soon as possible in order to get it fixed soon.
