### ISSUE TITLE
feat: custom layouts for list details

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#168]
The intent is to provide a way for users to create their own filters for data panels, with a default layout for everyone, that can be modified easily.

**Comment by Supamiu** [comment]
Here is how I'd see the thing:

- Open a dialog box to manage layout.
- Dialog should have possibility to import a layout from someone else (layout to json => to base64).

A layout is composed of panels, each of them has a filter and an ordering. An item can't appear twice in the layout, meaning that each panel gets data from the previous panel's unfiltered items.

The Other section is the last panel, where everything not filtered goes.

The Recipes panel is mandatory too and can't be edited, since we only want ingerdients to be filtered by layouts. Same for crystals.

**Comment by ayyaruq** [comment]
Being able to sort pre-crafts by job would be amazing, or also having a tree-view only for pre-crafts or all crafts but not the raw materials.
