### ISSUE TITLE
Failed to load character when try to search for character information

### ISSUE THREAD

**Issue by Duskraelea** [Supamiu/ffxiv-teamcraft#188]
When I input my character name and server, this error pop up in console

> Failed to load https://xivsync.com/character/search?name=Zeymoure&server=Tonberry: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ffxivteamcraft.com' is therefore not allowed access.

Could you please look into this ?

**Comment by Supamiu** [comment]
Hi, thank you for your report.

FFXIV Teamcraft uses xivsync to parse informations from lodestone and unfortunately it has a little issue at the moment so the service won't be available for a couple of hours (just need the author to be available to fix this).

Should be fixed asap, i'll close this issue once it is so you'll know what's happening 👍

**Comment by Supamiu** [comment]
It has been fixed, xivsync is back online.
