### ISSUE TITLE
bug: Rhea not found in alarms page

### ISSUE THREAD

**Issue by MrNeelix** [Supamiu/ffxiv-teamcraft#193]
Rhea was not found

**Comment by Supamiu** [comment]
Temporary fix is to type anything, clear it, and the results will show every nodes, Rhea is in them, strange thing is that it's not found by the search system, might be tricky, I'll check that for next minor update (3.2.1).

**Comment by Supamiu** [comment]
Alright, fixed it with some other bugs related to this search field, thank you for your report.

Once this issue gets closed automatically, it means that it's pushed to production and available to you.
