### ISSUE TITLE
feat: server side rendering for way better SEO

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#198]
The idea is to have SSR enabled with firebase to be able to have proper SEO.

**Comment by Supamiu** [comment]
https://github.com/angular/angularfire2/issues/1073

**Comment by arjunyel** [comment]
You dont need SSR for SEO :) https://www.youtube.com/watch?v=ANyOZIcGvB8

**Comment by Supamiu** [comment]
Rendertron seems interesting, but it's still SSR, as you are starting a chrome headless browser to server a html rendering of the page ;)

That being said, i'll check how this integrates with Angular, my main concern being database interactions. Thanks for the link, I was kinda stuck with SSR because of some requirements not being met by some of the libraries.

**Comment by arjunyel** [comment]
Yeah I should be clear, it is SSR but only for bots, humans get the regular browser based version

**Comment by arjunyel** [comment]
To address your edit I dont think SSR is necessarily a magic bullet for loading performance, SSR paints quickly but the number that actually matters in my opinion is time to interactive https://www.youtube.com/watch?v=wYGoJ8R3nnM

**Comment by Supamiu** [comment]
https://github.com/angular/angularfire2/issues/1685

**Comment by Supamiu** [comment]
Still can't do it, I'm getting some meaningless errors, will have to investigate later on...
