### ISSUE TITLE
Add a proper home page

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#20]
I'm thinking of adding a "list counter" to the main page, showing how many lists we currently have (we need Firebase Cloud Function for that).

The main interest of such a thing is to increase the "trust factor" of the application, because as a user, if you see that 1k+ lists are currently on the website, it's a proof that the website is useful.

**Comment by aluink** [comment]
I see value here. Can we re-purpose this issue to be a brainstorm/planning of a rework of the landing page?
