### ISSUE TITLE
feat: more intuitive representation of materials that have already been gathered and then used in pre-requisite crafts

### ISSUE THREAD

**Issue by sigilbaram** [Supamiu/ffxiv-teamcraft#200]
The way that Teamcraft handles materials that have been used in pre-requisite crafts isn't very intuitive or well automated and could possibly lead to discrepancies. All the math for completed gathering takes place in a single field, the same text field that users use, and this means that when updating the list users must account for this math.

For example, your FC is making a Large Shirogane Castle Walls. One of the materials required is 225 gold ingots.
* Someone contributes 5 Gold Ore, 5 Rasiqsand, and 5 Native Gold and marks them on Teamcraft. Teamcraft now says Gold Ingot 0/225, Gold Ore 5/225, Raziqsand 5/255, Native Gold 5/255.
* Someone else crafts those materials into 5 gold ingots and marks the gold ingots on Teamcraft. Teamcraft assumes this was crafted with other materials that haven't yet been inventoried and adds 5 Gold Ore, etc. Teamcraft now says Gold Ingot 5/225, Gold Ore 10/225, Raziqsand 10/255, Native Gold 10/255.
* Someone does inventory and realizes there isn't any Gold Ore, Raziqsand, or Native Gold on hand, only 5 gold ingots and marks this in Teamcraft. Teamcraft now says Gold Ingot 5/225, Gold Ore 0/225, Raziqsand 0/255, Native Gold 0/255. The inventory is now correct, however it doesn't properly reflect that some of the gold ore and such has already been gathered and then used to craft something else. This is in partly because the user didn't account for the gold ingots using those materials, but the tool should do that for them in some way aside from incrementing (possibly incorrectly) the same text field the user uses.

Of course the list should say Gold Ingot 5/225, Gold Ore 5/225, Raziqsand 5/255, Native Gold 5/255, or some variation there of, but with Teamcraft that requires a user to do some or even all of the math . Gold Ingots are also a relatively simple example, imagine this problem with something like Darksteel instead... I had to be careful keeping darksteel ore/nuggets/ingots straight yesterday even though I was working alone. Working with a group it would have been a mess for sure. Teamcraft being a group collaboration tool, it's even more important that this kind of inventory/quota system work in an intuitive way rather than relying on the awareness and/or math skills of each user.

**Comment by Supamiu** [comment]
A possible solution could be to provide a way to specify "I crafted from accounted materials" rather than always assuming that you only craft once you have everything, which is what is done right now.

So changing the amount of pre craft for an item wouldn't change the amount of its ingredients.

But the question is: how could it be done in terms of UX? How would a user do such a thing if it existed?

**Comment by Nivrelin** [comment]
How about a simple popup box? Lets say I'd add the 5 gold ingots. The teamcraft backend checks "Hey, there has been a tier 1 craft added, which had components that already existed in this list and the component wasn't completed. Send Popup box" -> The popup box simply asks the user "crafted from materials from list? yes/no" and according to the answer, the list gets refreshed.

**Comment by Supamiu** [comment]
Wouldn't it be too heavy in terms of UX? like each time you edit something you have to answer the popup, it feels boring for people who won't use it.

**Comment by sigilbaram** [comment]
Even if it didn't assume it was new materials and asked, there is still the possibility of there being a discrepancy if someone later goes back to do inventory, so it would be easiest if the text field was purely for entering the amount on hand, while the amount already used up was reflected somewhere else. As far as how to achieve that nicely in UX? On one had a popup might be messy, on the other it might also allow for more intuitive input in other ways. Such as being able to say "add 63" via a dialogue rather than having to do addition on whatever number is already there. Although I could also see where dealing with a popup constantly could be cumbersome...

**Comment by Supamiu** [comment]
Got an idea, considering the fact that list rows have two items for amount: `done` and `used`, used for inventory view (https://github.com/Supamiu/ffxiv-teamcraft/blob/master/src/app/model/list/list-row.ts#L18-L19).

Something like this could be easily implemented (pseudocode):

```
if(item.used < item.done){
    don't add items, simply update the used property.
} else {
    add items, as every items added have been used already.
}
```

So no dialog box needed, no specific behavior from the user, all handled automaticaly.

**Comment by Supamiu** [comment]
@sigilbaram I need to know if the solution above fits your needs before implementing it

**Comment by sigilbaram** [comment]
That would help with the issue of Teamcraft adding items when it probably shouldn't be, but it doesn't really address the usability problem of all the math taking place in the text field. That's kind of a separate, and likely more complex to fix issue, though.

Just as an existing example from an existing tool that I've used in the past, Crafting as a Service decreases the amount "Needed" by the amount used in pre crafts. That leaves their "Obtained" text field being just the amount on hand, instead of on Teamcraft where it is the amount on hand plus the amount used, which means the users need to math if they are trying to double checking inventory.

**Comment by Supamiu** [comment]
Hum, what if this was an option, like "Decrease amount needed when items are used" or something like that?

Might not be easy for users to find it, but if we put it in the Options page, it can be easily created.

**Comment by sigilbaram** [comment]
Hmm if something like that could be coded to work as an option, then that might work.

**Comment by Supamiu** [comment]
@Nivrelin https://github.com/Supamiu/ffxiv-teamcraft/blob/3.3.0/src/assets/i18n/de.json#L200 needs a bit of translation 👍
