### ISSUE TITLE
feat: Mark items as "working on it"

### ISSUE THREAD

**Issue by Pr0num** [Supamiu/ffxiv-teamcraft#205]
Since you usually don't check in every single item you gather and craft, it would be nice if (logged in) users could mark items as "in the works", to keep groups with bad communication from simultaneously mining 400 cobalt or the likes. For logged in users, it could say the character name, while for others it would just say "Someone."

Additionally, for crafted items, either mark the whole tree as being worked on, or give an option to mark just the craft or the whole tree.

**Comment by Supamiu** [comment]
So if you mark an item as "working on it" (I think that's how it'll be named), do you think it would be marked with your nickname on it or just "someone is working on it"?
