### ISSUE TITLE
ux: subheadings in layout are not visual higher than list rows

### ISSUE THREAD

**Issue by sigilbaram** [Supamiu/ffxiv-teamcraft#210]
The subheadings from layout options such as "Display crafting tiers" and "Area breakdown" do not appear higher level that the normal list rows and the different sections seem to blend together. Could be fixed with some slight style tweaks, such as increased `font-size` on headings, `font-weight: bold` on the headings, outdenting the headings, adding whitespace above the headings (wouldn't have to be large, just enough to  visually separate the sections), etc.

**Comment by Supamiu** [comment]
So you'd like to increase font-size of list headings? or just in the layout popup?

**Comment by sigilbaram** [comment]
The headings in the list itself. I messed around a bit and this CSS seems to work nicely.

```
.mat-list .mat-subheader, .mat-nav-list .mat-subheader, .mat-selection-list .mat-subheader {
    font-size: 15px;
}

.mat-list > div[_ngcontent-c35]:not(:first-child) {
    margin-top: 10px;
}
```

And when the compact list option is on:
```
.mat-list .mat-subheader, .mat-nav-list .mat-subheader, .mat-selection-list .mat-subheader {
    font-size: 15px;
}

.mat-list > div[_ngcontent-c35]:not(:first-child) {
    margin-top: 5px;
}
```

Just a small font size increase, and a bit of spacing to make the sections more distinct from each other.
