### ISSUE TITLE
feature: list diadem as a source of materials

### ISSUE THREAD

**Issue by sigilbaram** [Supamiu/ffxiv-teamcraft#212]
Several materials that come from timed nodes can be gathered at will in diadem, such as darksteel ore, spruce, native gold, etc.

**Comment by Supamiu** [comment]
Unfortunately, we can't know at the moment whether an item can be gathered from diadem or not, example: http://garlandtools.org/db/doc/item/en/2/6141.json

This uses Apricot, which can be gathered in diadem, but nothing related to diadem listed.

This cannot be done for now.
