### ISSUE TITLE
feat: sort inventory view using the same sort order as ffxiv

### ISSUE THREAD

**Issue by sigilbaram** [Supamiu/ffxiv-teamcraft#213]
If the inventory view sorted the same way as the in game inventory does, then it would make it easier to quickly compare the the two.

**Comment by Supamiu** [comment]
I'd have to know their sorting algorithm to be able to reproduce it unfortunately :/

**Comment by sigilbaram** [comment]
From what was said in Discord by Clorifex it seems like sort order would be something like `major category (not on garland atm) > minor category ("category" key from garland ) >  equip lvl ("elvl" key)> item lvl ("ilvl" key) > mystery field 18 (also not on garland, since it's not well understood, seems kind of like gear sets sometimes, but other times not)`. Although it might be nice to have this configurable, since the in game sorting can be changed by the user.

Skipping the major category wouldn't be ideal, but passable until the major category is available (unless that's easy to add of course). The "other" and "ingredient" minor categories would be messed up, since those would normally be split between 2 major categories, but at least everything else would be sorted for the most part.

Field 18, whatever it is, would only really come into play with gear that is all the same slot/elvl/ilvl from what I understand. Things like glamour items, but a lot of those have the same value anyway from what Clorifex was saying. Probably wouldn't be too common to have lists where this missing would be a problem?
