### ISSUE TITLE
bug: lists can created without names and can't be renamed afterwards

### ISSUE THREAD

**Issue by sigilbaram** [Supamiu/ffxiv-teamcraft#216]
I just created a list without a name. I tried to give it a name afterwards and it seems to be broken. https://ffxivteamcraft.com/list/DiDM0nUysNrrLlRDLtJz

Steps to recreate:
* Do a recipe search
* Click the button on an item to add it to a permanent list
* Select new list
* When asked to name the new list, click outside of the dialogue
* The dialogue box closes and a list with no name is created containing the item

The expected result would be cancelling the list creation, since clicking outside of this kind of dialogue usually cancels the action the dialogue is related to.

**Comment by Supamiu** [comment]
Gotta check if the name is empty before creating the list, if it's empty, then cancel the creation. If the user clicked outside, he probably wanted to cancel list creation.
