### ISSUE TITLE
bug: Black social media fabs on teal themes

### ISSUE THREAD

**Issue by Pr0num** [Supamiu/ffxiv-teamcraft#221]
While looking as intended on the orange themes, the white background changes to black due to `.mat-mini-fab.mat-accent`'s `color` being set from `white` to `rgba(0, 0, 0, 0.87)`.

**Comment by Supamiu** [comment]
Adding a `color: white !important` here: https://github.com/Supamiu/ffxiv-teamcraft/blob/master/src/app/app.component.scss#L72 should solve the issue, as these fabs won't change accross themes.
