### ISSUE TITLE
bug: lists not deleting after account creation (lists migration)

### ISSUE THREAD

**Issue by xbrico** [Supamiu/ffxiv-teamcraft#227]
Hello, just setup a new account. Was using this without an account and it has imported lists I was working on prior to having an account. It will delete some lists, some just seem stuck as empty shells...spinning circle when entering them to mark as complete and never load.

**Comment by Supamiu** [comment]
Hello, thank you for your report.

This issue is probably related to database rules, I have to dig into that but you can be sure that it'll be fixed for 3.3.0. Sorry for the inconvenience caused.

**Comment by xbrico** [comment]
Much appreciated. Thank you.

As a possible feature addition, generate a list code username. Means I can share a “List Link” or “User Link” and members of the FC can work on any part they wish independently. Easier to share into FC short message, etc.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Supamiu** [comment]
I'm not sure I understand the feature requests and how it would work, could you please elaborate this in a separate issue? I feel like it could be nice to have, but I'm not sure I understand the feature ^^

A user story would be the best for that, A.K.A write a guide on how to use the feature, as if it was already implemented.

**Comment by Supamiu** [comment]
could you please open the console (using F12 on chrome, console tab) and try to delete a list, then paste the error message displayed here, as either text or screenshot. I can't reproduce the error right now :/

**Comment by xbrico** [comment]
Evening,


All the stuck lists appear to have all disappeared now! :/


I'll see if i can reproduce at some point.


Apologies...but last night it was mental...they were deleting then coming back...something went weird.


________________________________

**Comment by Supamiu** [comment]
```
main.e421a0ab84bde730655f.bundle.js:1 ERROR TypeError: Cannot read property 'subscription' of undefined
    at n._next (main.e421a0ab84bde730655f.bundle.js:1)
    at n.__tryOrSetError (main.e421a0ab84bde730655f.bundle.js:1)
    at n.next (main.e421a0ab84bde730655f.bundle.js:1)
    at n._next (main.e421a0ab84bde730655f.bundle.js:1)
    at n.next (main.e421a0ab84bde730655f.bundle.js:1)
    at n._next (main.e421a0ab84bde730655f.bundle.js:1)
    at n.next (main.e421a0ab84bde730655f.bundle.js:1)
    at main.e421a0ab84bde730655f.bundle.js:1
    at t.invoke (polyfills.649a4245a702916f06a5.bundle.js:1)
    at Object.onInvoke (main.e421a0ab84bde730655f.bundle.js:1)
```

Someone reported me this error stack, might be useful.

**Comment by Supamiu** [comment]
Fixed ! thanks to Kokoro's help I could reproduce the issue and fix it 👍

**Comment by xbrico** [comment]
Hello,


this is still messed up for me in Firefox. The lists are still there, not deleting and "replicating".


Only error in console log (When i filter by error):


Error in parsing value for ‘display’. Declaration dropped. ffxivteamcraft.com:16:16<https://ffxivteamcraft.com/>

Error in parsing value for ‘display’. Declaration dropped. ffxivteamcraft.com:37:12<https://ffxivteamcraft.com/>
Error in parsing value for ‘display’. Declaration dropped. ffxivteamcraft.com:4:12<https://ffxivteamcraft.com/>
Error in parsing value for ‘height’. Declaration dropped. ffxivteamcraft.com<https://ffxivteamcraft.com/>
Error in parsing value for ‘height’. Declaration dropped. ffxivteamcraft.com<https://ffxivteamcraft.com/>
Error in parsing value for ‘height’. Declaration dropped. ffxivteamcraft.com<https://ffxivteamcraft.com/>
Error in parsing value for ‘height’. Declaration dropped. ffxivteamcraft.com<https://ffxivteamcraft.com/>
Error in parsing value for ‘height’. Declaration dropped. ffxivteamcraft.com<https://ffxivteamcraft.com/>
Error in parsing value for ‘height’. Declaration dropped. ffxivteamcraft.com<https://ffxivteamcraft.com/>
Error in parsing value for ‘height’. Declaration dropped. ffxivteamcraft.com<https://ffxivteamcraft.com/>
Error in parsing value for ‘height’. Declaration dropped. ffxivteamcraft.com<https://ffxivteamcraft.com/>


________________________________

**Comment by Supamiu** [comment]
Do you have the same error on chrome? What do you mean by "replicating"?

**Comment by xbrico** [comment]
It making a liar out of me today again...they have all disappeared now!

Best way to describe it is when I delete a list, its like it automatically regenerates it! Actually, as I type this, they have all reappeared again!!!!!! Its like there is a massive lag on it. Signing in, when clicking submit in chrome, the login box just sits looking at me.

(This must seem weird, I am typing as I do things)

Signed into Chrome, all the lists I have are there (Deleted multiple times in Firefox)

They seem to have deleted in Chrome.

Looks like now Chrome has deleted them, they have been removed from my Firefox Instance too!!! :/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
