### ISSUE TITLE
feat: workshops (list folders that can be shared)

### ISSUE THREAD

**Issue by xbrico** [Supamiu/ffxiv-teamcraft#228]
Hello,

as elaborated in a replay email. A possible nice feature to have would be, for want of a better term, user level list link.

Best example would be Github here. Instead of me linking several projects or lists in FC Chat/Short Message/Message board, I can share my top level folder of lists. Example as per Github addressing "https://github.com/Supamiu/ffxiv-teamcraft" in your instance on the website, it would be "https://ffxivteamcraft.com/lists/usernamecode" - it means I can short-link this into FC message board. Allows users to independently craft for the FC recipe[s] and allows low level crafters to see what they can contribute (to help their leveling grind) instead of specifying specific recipes/lists to work from.

**Comment by Supamiu** [comment]
Okay so the idea would be to share something like a folder? 

If that's it, here are my questions:

- Does it require read/write rights management?
- How do I specify what is the folder of each list?

**Comment by xbrico** [comment]
Hello,


I would drop the "target recipes" in as normal - airship, housing...whatever is going to have a multi phase approach. Set as a timed list...remove when completed as you already have. Essentially then, all I have to do is provide a link (or shortlink) to my "workspace" in your tool. They can then see all planned crafts. Rather than me creating lists and sub recipes to it and then linking each list separately. There is 1 single hyperlink I have to provide then and people can "on the fly" craft to their ability and sign off the mats (Tagging mat/craft sign off???) - means I know who to chase for what! :)

Could be left that only I, as signed in owner of the list can sign off the last part when the item has been created and collected.

It would less be "folders" and more a flat workspace. So, I suppose its like a dropbox idea...I just tell people where my projects live and they can go there...but they're not publicly searchable. That's where the idea of:
http://ffxivteamcraft.com/lists/<UUID code> <http://ffxivteamcraft.com/lists/<p>

would come into play...thats all I have to put on the FC board, people can go visit and craft to their level to help grind their alt up and at the same time, contribute to an FC craft.

Sub lists could still be doable, just as your site already allows - say to note priority of the project, etc. but really, the main thing is letting people access my listspace and an easy way to link all projects I am planning for the group to view and access.


________________________________

**Comment by Supamiu** [comment]
We could easily create a FC-only workshop (folder) by using `free_company` property on character data and by getting FC informations using https://xivsync.com/freecompany/parse/9235053248388268785 (example with my FC)

**Comment by Supamiu** [comment]
Update: FC workshops won't be available in first release, you'll be able to create, share and update workshops linked to your account, but no FC link for now.

**Comment by xbrico** [comment]
Hello,


Excellent and thank you for considering it as a feature.


________________________________
