### ISSUE TITLE
bug: undeletable quick lists after lag spike

### ISSUE THREAD

**Issue by EclipseBlade1871** [Supamiu/ffxiv-teamcraft#233]
I was adding masterbooks to my gatherers during a lag spike caused on my end. When the spike ended, I had 4 new quick lists added. 2 are Adamantite Jamadhars and 2 are Dragonskin Belts of Striking. One of each are able to be deleted, the others are cannot be opened or deleted. When I reload the list page, the deleted lists return. I tried merging them into one list and deleting them, but only one of the Adamantite Jamadhar lists was actually merged, leaving me with one Adamantite Jamadhar and 2 Dragonskin Belts of Striking bugged lists.

Update: Now one of the Dragonskin Belts of Striking stayed deleted, but now I have one of each of the items that cannot be deleted or opened at all.

**Comment by Supamiu** [comment]
Hi, thank you for your report 😃 .

Can you please link me one of the broken lists? you can get their link without opening them by clicking on the share button, it'll copy the url of the list in your clipboard.

I feel like this is related to #227 somehow, just have to find how ^^ having more input (like the links to these lists) should help me to figure out where's the problem.

**Comment by Supamiu** [comment]
I just pushed a fix to production that solves #227, if I'm correct, it should solve yours too, but I want to be sure of that, can you please check and tell me if it's fixed or not?

**Comment by EclipseBlade1871** [comment]
Sorry for the delay, life has been busy... Regretfully, the fix you were referring to did not remove the bugged lists. The Adamantite Jamadhars' link is https://ffxivteamcraft.com/list/5ShL3wh5kuaauH4gn4nV and the Dragonskin Belt of Striking's link is https://ffxivteamcraft.com/list/nNtyfWOmaGiLtpkTZrXG. In both cases, the loading circle just continues to go through its animation.

**Comment by Supamiu** [comment]
Could you please give me the email used for your account? Maybe on discord via PM if you're on it, would allow me to reproduce the bug easily.
