### ISSUE TITLE
Searching only returns a list of "name missing" items

### ISSUE THREAD

**Issue by Zweibach** [Supamiu/ffxiv-teamcraft#24]
When I search for something all items in the list are named "missing name" and clicking them redirects me to the start page.
![image](https://user-images.githubusercontent.com/10709426/30156755-cf8b8e06-93c0-11e7-9eb6-b528675ca52d.png)

**Comment by Supamiu** [comment]
What is your main language? I see that it's set on "SV" which should not be possible, that's why you have missing names, it's because SV names doe not exist.

I'll check this and probably add a guard for languages that are not in [FR, DE, EN].

Thank you for reporting this issue !

**Comment by Zweibach** [comment]
It works as it should now. In this case SV was for Swedish, my browser language or system language.
