### ISSUE TITLE
feat: multiple list layout system

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#244]
The idea is to have multiple layouts and be able to switch between them.

I'd see something like a dropdown menu where the actual layout button is, where you can select/edit layouts.

Not sure of how it'd be implemented/designed for now.

**Comment by ascobolonline** [comment]
Hi Miu, as said on Discord, here is a quick "drawing" how I thought it could go..
As info: In the dropdown on top, I would see the entries like this:

New
-------
Layout 1
Layout 2
.
.
.

So, if you select "New" "export" will be disabled. if you select an existing one, export is enable. Maybe it would be better to move the "Import" above the dropdown box into the left corner. and if you click it, the import dialog opens which additionally to the hash also asks for a name. 
Oh and you wouldn't need an edit button with this layout.. you just select the layout in the dropdown and it would fill the boxes below.
And then you can just save it.
so you would use the same form for "new" and "edit" and just prefill it via the dropdown (if not "new" is selected).
![layout_sketch](https://user-images.githubusercontent.com/3620177/36679655-09c6d140-1b14-11e8-92c9-325476bf4d7b.png)

**Comment by ascobolonline** [comment]
Here again with the import button moved to the corner
![layout_sketch_2](https://user-images.githubusercontent.com/3620177/36679809-6aaf716a-1b14-11e8-8e09-93a4dd18c6da.png)

**Comment by CostasAK** [comment]
I think you could take this even further.
Offer a small number of "factory default" layouts and a button to customize or make new ones. This way an inexperienced user does not get scared off by the large number of options that this menu presents. Many people using this tool will likely not be very experienced crafters (people helping in FCs) or might not be very tech-savvy.
Assuming the layouts get saved locally or on an account, it does not add many clicks to the flow of an experienced user either.
