### ISSUE TITLE
Searching Twice, Does not clear list if empty result

### ISSUE THREAD

**Issue by kiaka010** [Supamiu/ffxiv-teamcraft#25]
When searching twice does not clear the list when the first search populates the list, and the second has no results

Steps to reproduce
1) search "Iron Awl"
2) See results
3) add s creating "Iron Awls"
4) previous search not cleared

**Comment by Supamiu** [comment]
Thank you for reporting this, the issue seems to be that if the result set is empty, the last result is kept. 

I'll check this asap, it's not a blocking issue but it has to be fixed still :smiley:
