### ISSUE TITLE
bug: auto translated macro invalid in macro translator

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#252]
Problem
===
Consider you have a macro such as this:

![image](https://user-images.githubusercontent.com/556162/36813405-bf71448c-1cd4-11e8-991d-681b2db54294.png)

It will show up as invalid in the macro translator as shown here:
![image](https://user-images.githubusercontent.com/556162/36813549-40cd7dc0-1cd5-11e8-82d1-1847fa2dda22.png)

The reason is of course because it does not use `" "`, thus it is indeed an invalid macro in FFXIV as well. However when copying said macro it is copied this way, without `" "`.

Proposal
===
Instead of checking for `" "` in a given string just take everything between `/ac` until the end or until you hit a `<` (for `wait.` or `se.` commands) and try to translate that. If it is not a known skill it will not be translated either way.

**Comment by Supamiu** [comment]
Can you please paste an auto-translated macro here? So I have an example to play with 😁

**Comment by Supamiu** [comment]
```
/ac Inner Quiet<wait.2>
/ac Great Strides<wait.2>
/ac Steady Hand<wait.2>
/ac Advanced Touch<wait.3>
/ac Great Strides<wait.2>
/ac Advanced Touch<wait.3>
/ac Byregot's Blessing<wait.3>
/ac Careful Synthesis II<wait.3> 
```

**Comment by mihawk90** [comment]
A (probably) easier and (probably) failsafe way would be doing something like this to the string:

```JavaScript
// case 1
str = "/ac \"     Byregot's thingy\"    <wait.3>     "; str.substring(str.indexOf(" ") + 1, str.indexOf("<")).replace(/"/g,'').trim();

// case 1 result
// Byregot's thingy


// case 2
str = "/ac \"Byregot's thingy\"<wait.3>"; str.substring(str.indexOf(" ") + 1, str.indexOf("<")).replace(/"/g,'').trim();

// case 2 result
// Byregot's thingy
```

Pump that result into your existing translator object and you should be fine.
Not tested though since I don't have a working development environment currently.

**Comment by mihawk90** [comment]
OK, try number 2:

```JavaScript
var tests = [
    "/ac \"     Byregot's thingy\"    <wait.3>     ",
    "/ac \"Byregot's thingy\"<wait.3>",
    "/ac Bénédiction de byregot",
    "/ac Bénédiction de byregot<wait.3>",
    "/echo <se.1>",
    "/e <se.1>",
    "/micon Bénédiction de byregot",
    "/micon Bénédiction de byregot<wait.3>"
]

tests.forEach(function(str) {
    var action, actionEnd;
    actionEnd = str.indexOf("<");

    // reassign to end of string if no '<' can be found.
    actionEnd = actionEnd < 0 ? actionEnd = str.length : actionEnd;
    
    action = str.substring(str.indexOf(" ") + 1, actionEnd).replace(/"/g,'').trim();
    console.log(action);
});
```

Results:
```
Byregot's thingy
Byregot's thingy
Bénédiction de byregot
Bénédiction de byregot


Bénédiction de byregot
Bénédiction de byregot
```
