### ISSUE TITLE
feat: macros on lists

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#253]
Proposal
===

Being able to share macros alongside a given list would make public lists even more useful, thus it would be a nice addition.

Things to consider
===

1. Macros usually only work on specific stats/caps, so there should be a (required) field for minimum (and/or tested) stats required to work.
2. Attaching multiple macros for different caps would be a nice addition.
3. Adding a macro to a copied public list could make that macro visible for the original (public) lists author, he would then be able to test and approve that macro for public listing.

Optional features
===

Macro auto-translate in the macro list or a direct link to the macro translator with pre-filled macro.

**Comment by Supamiu** [comment]
I'm not sure this is something we want to integrate as a "built-in" feature, as it would require storing the macros etc.

That being said, you can use list's note to share macros with your list, something like: 

```
Macros for this lists : 
1500/1350/471 => https://pastebin.......
1650/1400/474 => https://pastebin.......
```

**Comment by mihawk90** [comment]
Yes that is definitely something for the interim.

A feature like this would not be anything for the near future anyway, just something that could be done at some point.

I think it would be nice to have something built in at some point to have all things gathering together.

Especially the storing and approving other people's macros would require some work since there is no relation between "master" (public) and "slave" (cloned) list as I understand.

**Comment by MDlumia** [comment]
this could be incorporated or made possible by linking it to a rotation from #331   now instead of just a macro as that would make more sense as it can make macros from said rotation.  and then people can see with their own stats if it would work. and could make tweaks to see if it would work.

**Comment by Supamiu** [comment]
Closing as you can share a rotation with the list, using a separate link, and the other user can save it and use it on the list.
