### ISSUE TITLE
feat: shard/crystal/cluster progress

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#254]
Proposal
===

Currently there is no progress for shards/crystals/clusters based on the (reasonable) assumption that most people are swimming in crystals.

However for large projects like leveling a crafting class this might not be true as you only start out with so many crystals. 

Things to consider
===

1. Most people will not care about crystal amounts so the current behaviour should stay in place as it is.
2. However there could be a checkbox to enable crystal progress tracking (maybe on a per-list basis).
3. The current layout should be unchanged, a reasonable solution would be to add progress beneath the current crystal display.

**Comment by Supamiu** [comment]
How would one input crystals in this configuration? Like, where should I put the input field? if you could create a mockup of how you're seeing it, even a shitty paint montage, it would be really useful to figure out how to implement that design-wise 😄

**Comment by mihawk90** [comment]
Let me show you the perfect art of my people:

![image](https://user-images.githubusercontent.com/556162/36933960-101bfa44-1ee2-11e8-9ab7-2330788f5c41.png)

Something along those lines.

**Comment by Supamiu** [comment]
Would this need to be stored as an account setting? a List setting? or maybe just a browser setting?

**Comment by mihawk90** [comment]
I think browser would be enough since it's more or less a personal thing.

Account would be OK too to have it active permanently.

The question is if the progress is being saved when you turn the setting off and back on (for example switching browsers). If it is, it doesn't really matter. If it not the setting should be cross-browser.
