### ISSUE TITLE
bug: template broken on outdated lists with reductions

### ISSUE THREAD

**Issue by TerasElexion** [Supamiu/ffxiv-teamcraft#258]
When hovering over the smaller UI elements in a list of materials to craft, the tooltip will pop up but not go away when moving the cursor off of the elements.  Using Firefox 58.0.2 (64-bit) on Windows 10 Professional.  Screenshot of the issue attached.
![teamcraft why](https://user-images.githubusercontent.com/36969220/36865829-a76cf810-1d5e-11e8-8ca7-0c2536c69c2e.PNG)

**Comment by Supamiu** [comment]
That's because you got a critical error that killed the change detector process, can you please take another screenshot with the console opened?

**Comment by TerasElexion** [comment]
![teamcraft why with console](https://user-images.githubusercontent.com/36969220/36873689-40b1a242-1d77-11e8-97fa-c16c909ed123.PNG)
Here's the screenshot with the same bug, and the console opened and what looks to be the error.  I have uBlock Origin installed but disable on Firefox, I'll try to see if I can duplicate on IE.

**Comment by TerasElexion** [comment]
Duplicated in list view on IE with nothing installed/enabled.

**Comment by Supamiu** [comment]
I made a fix and I'm pushing it to production, once this issue is closed it'll mean that the fix is live. If it's not fixed with that, please reopen the issue (after Ctrl + F5 the website to make sure you have the latest version)
