### ISSUE TITLE
bug: character not found

### ISSUE THREAD

**Issue by sanderbog** [Supamiu/ffxiv-teamcraft#260]
Cannot sign up: getting error character not found
Character: Sa Bo on Excalibur

**Comment by Supamiu** [comment]
The search query done behind is: https://xivsync.com/character/search?name=Sa%20Bo&server=Excalibur

As you can see, there's a 160 results, the first page only contains 50 of them, and your character is probably not in this part.

I can setup the lodestone link by hand if you can give me your lodestoneId (or a link to your lodestone profile) and the email used to sign in.

**Comment by sanderbog** [comment]
Just emails you

**Comment by Supamiu** [comment]
Alright, I binded it, should be resolved once you reload the page 👍 

I let you close the issue if it's resolved, to confirm everything is okay.

**Comment by sanderbog** [comment]
Works! Thank you!
