### ISSUE TITLE
feat: share a layout with a list.

### ISSUE THREAD

**Issue by MDlumia** [Supamiu/ffxiv-teamcraft#264]
**Proposal/idea**
The main idea would be to have be able to set a custom layout on a list or maybe a folder.  This would  help ease the flow of information  to those less Programmer/ tech minded. (EX. general FC mats, Crafting clients, casual crafters. and anyone who might not  have the time or whatever to learn how to import a layout.) 
**Benefits** 
1. it would ease adopting of the tool to a wider audience of people who may have different levels of technical knowledge,
2. it can make it simper on a lot of crafters who want to express what materials are needed to make a item in a simple easy to understand way.(much better then link spamming in party chat or pasting a huge list in to a discord dm, given how amazing the tool is at the moment.) Better just to make a list attach a "Default" layout and give them a link saying here's  the list of Everything needed to make said item.  then they can chose to  what lvl they want to give the mats to the crafter. 
3. the  big thing i learned with people is especially being on a RP server is people want to just know here's what i need heres where to get it, heres how to get it.  the tool is wonderful at telling you that. but it does have a some what steep learning curve for those who aren't technologically or logically minded. 
**Possible Tie-ins**
Issue #244 -  Could have the option to expand on this with the ability to take said  layout and import it to there personal library 
Issue #248 - If it goes successfully workshops could also have a default blanket layout simplfiying the  passage of info for fc crafts. again most people the simpler the better.(this is where this is, all this is said zone. ect.) 
**things to keep in mind**

- this shouldn't over ride a layout one already has. (provided it isnt the default layout) 
- it may be hard but in the end not all crafters and gathers/ users  have the knowledge to set it up before hand or the time. the old saying KISS Keep it simple stupid often works best for those people.
- this could be seen as a start on a basic mode compared to the full mode.
**Conclusion**
as you seen i have well thought out on this idea. im not to the point where i know how to proceed. yet it would be a boon to  the tool and might even lead to more patrerons if people like it enough.

**Comment by Supamiu** [comment]
Now that the default layout is a much more complete one that it was before, I think this isn't worth the effort (would require a lot of efforts). Closing it for now, will reopen if I see that people are asking for it.
