### ISSUE TITLE
feat: workshops in "add item to list" dialog

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#272]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
The lists that are sorted into workshop to appear in workshops in the list for adding recipes.
Similar to this:
![image](https://user-images.githubusercontent.com/556162/37245015-470e41e6-2492-11e8-8bd8-da0f530d4e6f.png)

The icon is [folder open](https://material.io/icons/#ic_folder_open).

## What is the use case for this feature?
When using a large amount of lists and they are organised into workshops (for me personally my public lists are in one workshop because I don't need them anymore, but are still public), having that organisation when adding a recipe would be helpful. I personally don't have a "lot" of lists, but most of them I don't use myself anymore (public only).

The workshop could be either closed or open, closed would be nice on very large lists, with a click opening it and listing the contents first.

**Comment by Supamiu** [comment]
https://material.angular.io/components/menu/api We could use menu sections for that.
