### ISSUE TITLE
feat: copy item name with /isearch macro

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#276]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
Since generating a macro to search for all items doesn't work out (see #266), it would be nice to be able to copy single items with a macro at least.
This should be optional though (like a "macro copy mode" checkbox at the top), since the user should still be able to copy only the item name with a click.

## What is the use case for this feature?
When you store a large amount of materials (in the various bags -____-) you can forget that you already had a certain item. Searching for every item and typing it would be somewhat tedious.

**Comment by MDlumia** [comment]
I agree with this one. would save me the hassle of manually keying in /isearch each and every time

**Comment by mihawk90** [comment]
AFAIK `/isearch´ always searches in the language your client is set at. So If you are using the game client in a different language then you are using TC, you'd need to toggle between languages between copy.

**Comment by CostasAK** [comment]
yeh, I think so too, but wouldn't that be annoying? I for one know a few people from Germany who play the game in their language, but do most everything else in English ( don't know why :p ). That doesn't really show how common it is, but at least it exists I suppose. Wouldn't be a priority, but something to think about maybe.

**Comment by mihawk90** [comment]
I don't mind either way. Double-Click seems reasonable since it's only useful PC anyway.

**Comment by Supamiu** [comment]
I just saw that a double click won't be possible 😞 because the clipboard system is using a directive, and I can't manipulate it from template code as it requires a DOM element to copy from, like jQuery implementations. What I can do tho is add an option that toggles a search icon next to the item's name, clicking on it would copy `/isearch <item name>` in your clipboard.

**Comment by mihawk90** [comment]
That would do as well (though whether a click on the name or a click on an icon copies it doesn't make a whole lot of difference).

Honestly I just fear that at some point there will be just too many icons next to the name and it makes it too cluttered :/
