### ISSUE TITLE
feat: crafting simulator link on craftable item

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#282]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
Links to crafting simulators on craftable items, so no need to search on them anymore.

The link would be like this:
http://ermad.github.io/ffxiv-craft-opt-web/app/#/recipe?lang=en&class=Alchemist&name=Growth%20Formula%20Alpha

Documentation for the link is here:
doxxx/ffxiv-craft-opt-web@6de00a851f20faffb45aabe10a67f682ef0555ae

This could also be a setting in the settings pane since some people seem to prefer a specific fork of the sim.

That setting could also overwrite the link on a craftable item to not link to the specified database, i.e.

```
Item links
    select
      |- XIVDB
      |- garland
      |- gamerescape

  [ ] use crafting sim link on craftable items instead
    select
      |- lokyst
      |- ermad
      |- ryan20340
      |- custom(?)
```

Might as well use an input field to input the base URL of the preferred crafting sim.

**Comment by Supamiu** [comment]
Won't be done for now, as I need to add some informations to the current link system (recipeId isn't in the link informations, which means I can't get the recipe to be linked properly).

**Comment by mihawk90** [comment]
Hm, the link only takes the name, so I assume you mean for inserting the "correct" profession in the link? I was just thinking, why not add the crafting link on the profession icon instead? Currently they have no function except the tooltip. That way the profession can be chosen on demand by different people.

If crafter1 has BSM on 50, and crafter2 has ARM on 50, then crafter2 can craft the same ingots, but a link to a BSM simulator isn't helpful.
