### ISSUE TITLE
feat: Icon only version of left menu.

### ISSUE THREAD

**Issue by CostasAK** [Supamiu/ffxiv-teamcraft#294]
## I'm submitting a...
* (X) Feature request *

## What feature are you proposing
A button that collapses the left menu into a slimmer version with only icon. Icons would show their name on mouse-over, in a small pop-up similar to other mouse-over pop-ups. See mock-up:
![image](https://user-images.githubusercontent.com/23523864/37866815-06b9d2e6-2f90-11e8-9e1b-fd6a70b98e31.png)
![image](https://user-images.githubusercontent.com/23523864/37866928-753db3b2-2f91-11e8-8f6b-8aa7b9a10952.png)

## What is the use case for this feature?
- Less than full-hd screens gain some space.
- People who use display scaling gain some space (very nice on laptops)
- Provides more focus on the list (helps with concentration)

**Comment by Supamiu** [comment]
That's a very nice idea ! Thank you for the suggestion

**Comment by Supamiu** [comment]
![image](https://user-images.githubusercontent.com/11519203/37969104-45553e2c-31d0-11e8-8059-34268cf2d355.png)
Here is the version that will be pushed to production very soon (probably today).
