### ISSUE TITLE
feat: nicer scrollbars (UI theming)

### ISSUE THREAD

**Issue by CostasAK** [Supamiu/ffxiv-teamcraft#295]
## I'm submitting a...
* (X) Feature request *

## What feature are you proposing
Sites like GarlandTools use custom scrollbars to fit in nicer with the overall site theme. Grey Windows scrollbars are pretty horrid.
I'd like them especially on the left menu and tooltips, but if it's not too much work on the lists it would be pretty nice as well.

## What is the use case for this feature?
Makes the left menu appear less "cut-off" by a scrollbar when it's needed.
Provides a more consistent theme for the site.
Less intrusive UI elements => more zen experience.

**Comment by mihawk90** [comment]
Pro tip of you're using Chrome (or other chromium based browsers), this is already possible.

See
chrome://flags/#overlay-scrollbars

**Comment by Supamiu** [comment]
I tend to agree with @mihawk90 , it's really hard to integrate something like perfect scrollbar in an angular environment, if I find a way to enable that, I'll do it for sure but for now I can't 😞

**Comment by CostasAK** [comment]
Maybe Clorifex has an idea? it's just that when the scrollbar comes on the left-frame, it looks like the 90's came back for a vengeance. ;p

**Comment by Supamiu** [comment]
Pasting this here for further investigation: https://www.npmjs.com/package/ngx-perfect-scrollbar (no time to check that today but I'll check for sure)

**Comment by CostasAK** [comment]
I would agree that practical features would take priority of course, if this is really hard. I can't really judge the difficulty, since I only ever make cli software haha.

**Comment by mihawk90** [comment]
> though right now I dont have scrollbars at all because of it

well, that's the point of that setting (kind of) they are overlayed and transparent on top of the content, they do appear when you scroll or hover over where they are supposed to be.
It's basically mimiced from what Mac OS had since pretty much forever.
