### ISSUE TITLE
Can't log in or sign up

### ISSUE THREAD

**Issue by SvAsp** [Supamiu/ffxiv-teamcraft#298]
Hi!

Thanks for your help in advance!

I can't log in or register with my google account. I suspect I may have this exact same issue: https://github.com/Supamiu/ffxiv-teamcraft/issues/192. I just don't remember if I logged in with Google before registering.

My Google account is svenaspers@gmail.com.

Have a nice day and thanks for checking!

**Comment by Supamiu** [comment]
Hi, because you tried to log in before registering, it created a weird state in the database with your account (I'm working on removing this issue). I deleted your account from the database so you can register a new one and then login, it should work like a charm.

**Comment by SvAsp** [comment]
Thanks, it worked like a charm indeed!
