### ISSUE TITLE
feat: change community list behaviour

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#307]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
As discussed earlier in Discord, community lists need some clean up, as there are currently a *lot* of useless/trash lists (mostly from when they were called public and people set them public just to share).

A good place to start would be setting all community lists without tags and/or descriptions back to private (maybe start with lists without tags, with a grace period for lists without description).
I would expect that the people that actually care about their lists have them tagged already anyway.

Additionally I propose that lists can not be set to community lists as long as there are no tags as minimum requirement. The checkbox could just be straight up disabled with a hint what's up. It could also show a warning when there is no description set (above the checkbox, not at the very top this time ;)).

Requiring description would be a bonus, though some tags are self-explanatory and need no description, so not sure if it should be required (as it could end up in trash descriptions in turn).

What could help as well is a rating system so users can vote on good lists (copy counter isn't really a good indicator IMO). Comments are a little problematic at the moment since it's hard to keep track of them as the list owner (notifications already WIP).

/edit
another criteria: single-item lists should not be allowed because there's temporary lists for that.

**Comment by AltanRapsied** [comment]
Issue with rating system is that people can bypass it by using multiple account and/or asking friend's approval. Copy number is a real indicator as to how useful is your list, and IMO if it hasn't been copied a single time within a month it has nothing to do in community list.

**Comment by AltanRapsied** [comment]
This would be really tough to implement because when you set a list to public that'd mean you'd need to compera it with every public list, item per item. No need to explain how slow this process would be.

**Comment by mihawk90** [comment]
Yes, that's why suggested a background task.

I don't know how the database works internally so I'm not sure if filtering for amount of items for example would be possible, to reduce the amount of lists to compare to.
