### ISSUE TITLE
feat: Optimize gathering list sort for teleport costs

### ISSUE THREAD

**Issue by NikolasCalypso** [Supamiu/ffxiv-teamcraft#313]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
"Browser:": Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Have you disabled script-/adblockers before submitting? Yus

## Current behavior
The order of teleports costs too much gil.

## Expected behavior
The order of teleports to cost less gil.

## Steps to reproduce
1. Make a list
2. Observe un-optimized route
3. no profit

## What feature are you proposing
Optimize, or at least add the option for optimizing locations to teleport to for distance/gil cost.
The last list I made up takes me from South Shroud -> Upper La Noscea -> North Shroud.
I haven't counted the steps, but I suspect going to ULA, then North, then South would be better. 

## What is the use case for this feature?
Saves gil when teleportating around to gather a bunch of materials. Granted, it isn't a lot each time, but they all add up and cut in to the bottom line.

**Comment by Supamiu** [comment]
Hi, thank you for your feature suggestion 👍 

Where would this appear? I see it being a button on a zone-breakdown panel in the top, or directly list zones ordered by cost in the breakdown.

Anyways that's a nice idea, I'll add this to 3.5 for sure

**Comment by NikolasCalypso** [comment]
Rolling this around in my head a bit, I would like to see sorting/filtering implemented across the site. IMO, it is a key indicator of an "HQ" site, and you certainly have a lot of points in the HQ category. My first suggestion on Discord was about sorting pre-crafts by job, which is a bit different, but same category.

I'm not the best at UI, but I'm thinking if you had a "filter/sort" button which popped up a little panel where you could choose how you want to sort and whatever options are relevant for the panel that is being sorted. As for the starting location, guests could type it in here, and registered users could set it in there profile (if they set their free teleport destination it gives them an optional free starting point). This should leave it up to them if they want to do that extra free teleport to save a bit or not, and make it really easy on you, as you have a static starting point for each user.

That's my 2.5 gil. Looking forward to 3.5! Keep up the great work! :)

**Comment by Supamiu** [comment]
Starting point could be something like one of the housing zones, you get to choose one or it uses the default one (I'd say shirogane since it's probably the most populated).

Have you tried the layout feature? That's what I created to give people a way to customize their list display and ordering, I can add more ordering in there. There's just two panels not in this feature: crystals and items, but I'll integrate items "a bit" for #296

**Comment by Supamiu** [comment]
Delayed to 3.5.X because it needs some adjustments to the data I'm extracting from the client.

**Comment by Frostpaw** [comment]
re: traveling salesman issue, why not have an email account variable set for FC buff costs and free/favored saves, while somebody with gil can burn time compiling a list of gil values by a certain aetheryte?
