### ISSUE TITLE
bug: trying to log in with an unverified account triggers email verification spam

### ISSUE THREAD

**Issue by MorpheusXAUT** [Supamiu/ffxiv-teamcraft#316]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Have you disabled script-/adblockers before submitting? - **No**

## Current behavior
Logging into an unverified account requests the user verifies their account via email. Doing so resulted in multiple verification emails being sent within a few minutes (97 in 7 minutes to be exact). Since every new email seems to generate a new confirmation link, it does not seem possible to verify the account either. After clicking the last link, the account was still reported as unconfirmed and could not log in anymore (always showed up as "anonymous").

## Expected behavior
Single verification email is sent out, allowing for the account to be properly verified.

## Steps to reproduce
1. Log into unconfirmed account
2. Agree to confirm account via email
3. Receive multiple verification emails (?)

I'm reporting this issue for an FC member without a GitHub account, so have no experienced it directly myself unfortunately.

**Comment by Supamiu** [comment]
Hello, thank you for your report 👍 

I found the issue and fixed it for 3.5.0 😄

**Comment by MorpheusXAUT** [comment]
Glad to hear it could be resolved so quickly, thank you very much for your work!

**Comment by Supamiu** [comment]
Issue still not fixed apparently, reopening the issue for tracking purpose
