### ISSUE TITLE
feat: contacts system

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#319]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing

The idea is to be able to add some users as friend using user Id or email.

## What is the use case for this feature?

When I'm creating lists and I want to share them with my friends, I don't want to remind their user ID each time, being able to select them from a dialog box would be way easier.

**Comment by ascobolonline** [comment]
My idea here was, to add a friend once via UID (ofcourse you have to share it once). And once you added it, it stays kinda "greyed out"/inactive, at the same time, the friend gets an email with a link to accept the friend/contact. if he clicks the link, the contact becomes active and is added to both contact lists. if one of them deletes it, it is deleted on both sides as contact, but ofcourse could still stay in permissions etc.
On the permission dialog you could have the dialog as now and just add a button "select contact", which will insert the uid into the form. So the email of a user stays private.

**Comment by Supamiu** [comment]
My original idea was to simply add the ability to add someone in a kind of "favorite users" list, without the other user being notified or anything, just that. So you can find users easily when playing with permissions.
