### ISSUE TITLE
feat: Badges system for a sense of pride and accomplishment

### ISSUE THREAD

**Issue by Tataru-Taru** [Supamiu/ffxiv-teamcraft#322]
## I'm submitting a...
* (x) Feature request 
> Proposed by: S'irle "Shirley" Alythia

## What feature are you proposing.

A badge system that shows *Achievements* done on the website.
 ```Examples: patreon badge, list maker badge, donor badge.```

## What is the use case for this feature?

Upon completion of certain tasks, or assisting the site in other ways, badges would be added to your public profile.

**Comment by AltanRapsied** [comment]
Patreon badge is actually a thing already but it's not automized, I wonder if it can be. That would probably requier to link both or the use of same email.
