### ISSUE TITLE
feat: gear calculator,similar to the now defunct FFxivcrafting 

### ISSUE THREAD

**Issue by MDlumia** [Supamiu/ffxiv-teamcraft#329]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (X) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
I am proposing a craft able gear calculator, akin to the one that the now  supposablty  abandoned FFXIVCrafting site had. 
## What is the use case for this feature?
lets say one needed to level up a new class and you wanted to craft gear for said class. one would just select class select level and have a list of crafts or options made available. said list could be made in to a teamcraft list and then used with any of the wonderful features the tool has.  i know garlond tools has something similar yet it doesn't support exporting in to TC so those who are use to the TC tool have no way but manualy finding the items and adding them to a list.  so it would be best to have a inhouse solution.

**Comment by Supamiu** [comment]
Will be done inside #485 , closing this one.
