### ISSUE TITLE
feat: Frequent Craft list/Favorite craft list. 

### ISSUE THREAD

**Issue by MDlumia** [Supamiu/ffxiv-teamcraft#334]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (X) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
A  Frequent craft list  or favorite crafts list feature for convenient access to commonly crafted items.  to add them to like a list or a temp list. 
## What is the use case for this feature?
use is convenience for often crafted items by the person. so they dont have to keep searching for the items each time. saveing time and patience

**Comment by Supamiu** [comment]
Closing as I don't see a way to properly do that now or in the future without stressing the database a lot 🙁.

I'll reopen if I find a way to do it properly.
