### ISSUE TITLE
feat: Gathering/Material Lists

### ISSUE THREAD

**Issue by TheMegaMatt** [Supamiu/ffxiv-teamcraft#336]
## What feature are you proposing
Allow to create lists that contains materials only. 
## What is the use case for this feature?
Case 1: I'm crafting a battle set for someone and i want them to provide some of the materials, instead of linking them the full list which they have no interest in seeing the full list but just the ones that they need to provide.

Case 2: inventory stock management, lets say i want to refill my inventory with certain materials at the moment i need to put completed items, like ingots and such but what if i want to stack up on Flax for example

**Comment by Supamiu** [comment]
related to #80

**Comment by TheMegaMatt** [comment]
so is this do-able?

**Comment by ascobolonline** [comment]
Also could be used to "collect" materia for a set meld etc
