### ISSUE TITLE
Bug: These two items in one list cause wrong amount of Darksteel Nuggets

### ISSUE THREAD

**Issue by Tataru-Taru** [Supamiu/ffxiv-teamcraft#337]
## I'm submitting a...
* (X) Bug report *- please add **bug:** before the title*

### Browser

Have you disabled script-/adblockers before submitting?
Yes
### Teamcraft Link
https://ffxivteamcraft.com/list/yx3Us91Ddu8MQjqHBrSU

## Current behavior
If you have these 2 items in a list, it asks for an additional 36 nuggets. 

## Expected behavior
Recipes uses 120 darksteel nuggets, confirmed this by making a list of each item seperately, no issues. Also no issues with different item combinations with paired with either item.

## Steps to reproduce
1. Create list with: Viltgance-type Aetherwings , Odyssey-type Forecastle
2. Click final items as completed.
3. Notice that it shows 120 nuggets, and item is completed.

**Comment by Supamiu** [comment]
Seems like this was an issue on garlandtools' side, I made a copy of your list, regenerated it and the bad amount went away. Can you confirm it's fixed @Tataru-Taru @CostasAK ?

**Comment by CostasAK** [comment]
I recreated the first list of the report and checking off all crafts that had the HQ symbol. Same issue persists. Final crafts are shown blue while darksteel nuggets and cobalt ingots are still white and needed.
Created the same list on garland, there it works, if that is any indication of anything.
