### ISSUE TITLE
bug: Crafting Rotations reappearing out of nowhere

### ISSUE THREAD

**Issue by Pokefan5** [Supamiu/ffxiv-teamcraft#355]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
FFXIV Teamcraft Desktop App [4.0.3]

## Current behavior
When modifying crafting classes in the 'Profile' tab, after saving deleted crafting rotations reappear and my tab is changed to edit them.

## Expected behavior
When modifying crafting classes in the 'Profile tab, after saving the 'Profile' tab is still selected.

## Steps to reproduce
1. create and delete a crafting rotation
2. modify and save one crafting class (stats or books)
3. bug occurs

In case my description of the bug is unhelpful or otherwise inaccurate I have uploaded a short video demonstration: [https://youtu.be/eYzmAVQ6c44](https://youtu.be/eYzmAVQ6c44)

**Comment by Supamiu** [comment]
Hey, thank you for your bug report, i'll do my best to reproduce it and fix it in a patch version.
