### ISSUE TITLE
bug: Auto updater just uninstall old version but doesn't install new version.

### ISSUE THREAD

**Issue by SuperJugy** [Supamiu/ffxiv-teamcraft#359]
## I'm submitting a...
* (x) Bug report *

### Browser
Windows app :smiley: 

Have you disabled script-/adblockers before submitting?
N/A
### Teamcraft Link
N/A
### Layout code
N/A

## Current behavior
After installing the windows app, the autoupdater says you need to restart the app. After restarting, the updater uninstalls the old version but won't install the new one.
## Expected behavior
The updater should update :stuck_out_tongue_closed_eyes: 
## Steps to reproduce
1. Install the new windows app and select "for all users" option instead of only current user.
2. Complete the rest of installer with default values and run app.
3. After updater prompts to restart, restart. uninstaller should run (windows UAC will prompt for admin privileges)
4. Try to find the windows app.
5. Discover that it is gone.
6. Cry in corner.
7. ???
8. Profit!!!

**Comment by Supamiu** [comment]
This is most likely due to the fact that installing for all users requires admin permissions, but when you start the app, you're not admin, so it will delete the old version but can't install the new one, see https://github.com/electron-userland/electron-builder/issues/2363
