### ISSUE TITLE
feat: replace lists buttons with bottom sheet and add actions

### ISSUE THREAD

**Issue by AltanRapsied** [Supamiu/ffxiv-teamcraft#360]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (X) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
Replace most of the buttons of a list with bottom sheet (because they'r egetting too numerous and obnoxious)

## What is the use case for this feature?
Use bottom sheet to replace the buttons of a list on the list page. https://material.angular.io/components/bottom-sheet/overview
Buttons lefts are below.
|Actions| |Open| |Dropdown|

Open is the already existing button that open the list, and dropdown is the already existing arrow to quickly show the list's items.
Clicking on actions would show the bottom sheet with the following actions :
**Description**
Edit the list's description.
**Tag**
Edit the list's tags.
**Template**
Set the list's template.
**Permissions**
Manage other's permissions for this list.
**Share**
Copy the link of the list to share it wherever you want.
**Custom link**
Create a custom link with the name you want for this list.
**Delete**
Delete the list.
Warning: unreversible.

Most of them are already existing buttons. 2 new ones are **Description** and **Tag**.

**Comment by Supamiu** [comment]
I added some translations for this issue in the translation files, see https://github.com/Supamiu/ffxiv-teamcraft/commit/5a469033dae61e8f8065e7b99db029a672e08397
