### ISSUE TITLE
bug: missing Duskglow aethersand info

### ISSUE THREAD

**Issue by MDlumia** [Supamiu/ffxiv-teamcraft#362]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
*Please state your browser and version. Go [here](https://ipchicken.com/) and copy everything after 
Windows 10 Teamcraft app 4.0.5

Have you disabled script-/adblockers before submitting? N/A

## Current behavior
Dusk Glow aethersand has no timer and no location info in the app
## Expected behavior
that it has the proper info listed
## Steps to reproduce
1.  Go to ether gathering items or have a list that needs that.
2. look for icon to bring up detals (its not there)

**Comment by Supamiu** [comment]
This was coming from a cache issue on garlandtools side, regenerate your list to make sure it's up to date, just tested and it's finally here 😄 

![image](https://user-images.githubusercontent.com/11519203/40471568-5636408a-5f37-11e8-9eba-72df0421a3f8.png)
