### ISSUE TITLE
bug: Copying macros in Firefox-based browsers ignores new lines.

### ISSUE THREAD

**Issue by iriscal** [Supamiu/ffxiv-teamcraft#367]
### Browser
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 

## Current behavior
When copying a macro to FFXIV, pasting it outputs it all on one line.

## Expected behavior
When pasted into FFXIV, the macro should be split up into one command per line.

## Steps to reproduce
1. Open recipe
2. Click Generate Ingame Macro
3. Copy text.
4. Paste text in FFXIV macro window.

**Comment by Creatan** [comment]
Seems to be indeed related to firefox, but other sims seem to be working fine. Then again they use `textarea` with line-endings and teamcraft has each line wrapped in a `span` that might be the issue.
