### ISSUE TITLE
bug: Innovation isn't enclosed in quotes in generated macros.

### ISSUE THREAD

**Issue by iriscal** [Supamiu/ffxiv-teamcraft#369]
### Browser
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

## Current behavior
When generating macros, Innovation is not enclosed in quotes.
Curiously, this happens in both the "Ingame Macros" and "Cross-Class skills setup" sections, suggesting that this may be specific to the skill, not the generated macro.
https://imgur.com/a/wI0mcQQ

## Expected behavior
Innovation should be enclosed in quotes.
https://imgur.com/a/YFqB9Yt

## Steps to reproduce
1. Create or open a rotation which uses Innovation
2. Click "Generate Ingame Macro"

**Comment by Supamiu** [comment]
That's because ingame macros don't require quotes if they don't have space in their name, so the generator only puts quotes if they're needed.

**Comment by iriscal** [comment]
I see!
