### ISSUE TITLE
bug: Speciality: Refurbish completely refills CP bar

### ISSUE THREAD

**Issue by Nithayan** [Supamiu/ffxiv-teamcraft#371]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
Using the desktop client, version 4.0.7.

Have you disabled script-/adblockers before submitting?
Not relevant as I'm using desktop client.
### Teamcraft Link
*If the bug appeared on a list (i.e. layout issues), please put a link here.*
### Layout code
If you're reporting a layout issue, please give us the layout code
```
Paste your Export code here
```

## Current behavior
Upon using the action "Speciality: Refurbish", the entire CP bar is refilled
## Expected behavior
The action should only replenish up to 65 CP.
## Steps to reproduce
1. Open Simulator
2. Deplete CP by any amount
3. Use Speciality: Refurbish

**Comment by Supamiu** [comment]
Hello, thank you for your report 👍 

This is fixed and will be shipped in 4.0.8 release 😄
