### ISSUE TITLE
Desktop app gets stuck on regenerating all lists -> needs restart

### ISSUE THREAD

**Issue by ascobolonline** [Supamiu/ffxiv-teamcraft#374]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
*Please state your browser and version. Go [here](https://ipchicken.com/) and copy everything after "Browser: Desktop App

## Current behavior
Regenerating all lists gets stucked and you have to close the whole app to get out of the dialog

## Expected behavior
Maybe somehow a cancel button or reload button to get back to the "startpage""listpage" of the desktop app.

## Steps to reproduce
1. Regenerate all lists in dekstop app (happens not everytime)

**Comment by Supamiu** [comment]
might be fixed with 4.0.8, needs check :)

**Comment by Supamiu** [comment]
Closing as fixed for now, please tell me if you can reproduce it, I'll reopen the issue if it's reproducible.
