### ISSUE TITLE
Desktop app opens window without closing button

### ISSUE THREAD

**Issue by ascobolonline** [Supamiu/ffxiv-teamcraft#375]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
*Please state your browser and version. Go [here](https://ipchicken.com/) and copy everything after "Browser:" Desktop app

## Current behavior
If you get the message popip that there is a new version available and you click the download link, it opens the github download site in a new window (of the desktop app, not in a browser) which has no closing buttons.. so to close it, you can hit Alt+F4 on PC but that is not really user friendly ;-)

## Expected behavior
Have some kind of closing button to close the new opened window.

## Steps to reproduce
Couldn't reproduce as the dialog doesn't appear again once the new version is installed.. :(

**Comment by Supamiu** [comment]
Becayse the auto updater and window state management have been improved since, I'm closing this issue as a window without close button shouldn't happen anymore. Will reopen if it does.
