### ISSUE TITLE
bug: Incorrect progress on simulator

### ISSUE THREAD

**Issue by ayyaruq** [Supamiu/ffxiv-teamcraft#378]
### Browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

## Current behavior
1600 craftsmanship (lv70) on lv65 rlvl 276 (slate grinding wheel) with action Careful Synthesis III does 757 progress. Probably an issue with level modifier.

## Expected behavior
1600 craftsmanship (lv70) on lv65 rlvl276 for action CS3 should do 761 progress.

## Steps to reproduce
1. Use the action with custom stats
2. Look at progress
3. Profit, because you complete the craft in less steps I guess

**Comment by Supamiu** [comment]
Data sheet for math work : https://docs.google.com/spreadsheets/d/1sbML4wcNFOPcOuSm2TCoKvivHo_T_2HY1VfeI7nCnug/edit#gid=741735387
