### ISSUE TITLE
feat: add filters for recipe search field

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#38]
Filtering on the following properties of an item could be really good:

- [x] ilvl
- [x] required level
- [x] worn by
- [x] crafted by

**Comment by HoninboDosaku** [comment]
Using the same idea, maybe it would be possible to "add recipes" as a batch. As in "add every cloth-type material" or "leather-type".  Would be more efficient to delete just one or two after importing, when you need a lot of them in your list, than add them one by one.

**Comment by Supamiu** [comment]
Here is the user story that I would implement to suit your idea @HoninboDosaku : 

- Click on the "Add multiple items" button, it becomes a "confirm" button.
- Each result row now has a checkbox (amount field might be disabled during this, and forced to 1).
- Select the items you want to add.
- Click on the confirm button, which will ask you for the recipe to add items into.

This might be hard to implement tho, I might create a new issue for this feature because it seems like a ton of work at first glance.

**Comment by Supamiu** [comment]
I added one more search type: craft level.
