### ISSUE TITLE
bug: Innovative Touch in the simulator doesn't decrease durability

### ISSUE THREAD

**Issue by Curchack** [Supamiu/ffxiv-teamcraft#386]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*

### Browser
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 

Have you disabled script-/adblockers before submitting?
Yes.

## Current behavior
Using the Innovative Touch action doesn't decrease the durability of the item.

## Expected behavior
Using the Innovative Touch action should decrease durability.

## Steps to reproduce
1. Simulate crafting any recipe as any class, specialist, level at least 56.
2. Add the Innovative Touch action.
3. Durability doesn't decrease.

**Comment by Supamiu** [comment]
Hello, thanks for the bug report 👍 

I'll get this fixed asap, will probably be deployed during the evening.
