### ISSUE TITLE
Feat: Shared Inventory View

### ISSUE THREAD

**Issue by TheMegaMatt** [Supamiu/ffxiv-teamcraft#391]
## I'm submitting a...
* (_) Feature request *- please add **feat:** before the title*

## What feature are you proposing
have the ability to see individual inventory when more than one people are working on a list

**Comment by Supamiu** [comment]
If I understand properly, the idea is to know what each contributor is supposed to have inside his inventory at a given time?

**Comment by TheMegaMatt** [comment]
Yep

Il sab 2 giu 2018, 17:58 Flavien Normand <notifications@github.com> ha
scritto:

**Comment by Supamiu** [comment]
This can't be done for now, as the website doesn't record who contributes items. So it's not able to say who is supposed to own what.
