### ISSUE TITLE
feat: Minimum Quality required for 100%

### ISSUE THREAD

**Issue by iriscal** [Supamiu/ffxiv-teamcraft#398]
## What feature are you proposing
In the crafting simulator, when applying a rotation to a specific recipe, show the minimum starting quality required to hit 100% with a user's stats and rotation.
## What is the use case for this feature?
The user would gain at-a-glance information without having to take extra steps to calculate.

**Comment by Supamiu** [comment]
I don't know if adding this wouldn't be a kind of "too much text" feature, while you can do TotalQuality/maxQuality to have missing starting quality.
