### ISSUE TITLE
bug Airship/submersible compos not showing where they can be found

### ISSUE THREAD

**Issue by Chapaille** [Supamiu/ffxiv-teamcraft#399]
## Environment
Desktop application version 4.1.3

Have you disabled script-/adblockers before submitting?
### Teamcraft Link
https://ffxivteamcraft.com//list/La1CmEi6sj27v0qnacg5

## Current behavior
The Aurelia Polyp does not show which submersible areas you can get it from.

## Expected behavior
Compos from airship/submersible areas should show where they can be collected or at least show that they are collected from airships/submersible areas. 

## Steps to reproduce
1. Create a list with some you need from airships. Jellyfish lantern for example.
2. Go into list and look at Aurelia Polyp.

![image](https://user-images.githubusercontent.com/39924333/40936111-8615ce7c-683a-11e8-88b7-aaf68bfb609b.png)

**Comment by Supamiu** [comment]
That's a known issue, it's because these informations aren't extracted from game, they are hand-filled. A lot of them are missing and we need to add them in Clorifex's data sheet (see discord #general pins).

**Comment by Felys1998** [comment]
Best available collections of airship and submersible data that I know of:

http://forum.square-enix.com/ffxiv/threads/245872-Airship-Guide

http://forum.square-enix.com/ffxiv/threads/357591-Submersible-Information-Thread

**Comment by Supamiu** [comment]
If somebody has the time/motivation to contribute to this sheet, it holds additionnal informations for garlandtools (so, in the end, for Teamcraft): https://docs.google.com/spreadsheets/d/1hEj9KCDv0TT1NiGJ0S7afS4hfGMPb6tetqXQetYETUE/edit
