### ISSUE TITLE
BUG: Dungeon icon linked to wrong location.

### ISSUE THREAD

**Issue by Tataru-Taru** [Supamiu/ffxiv-teamcraft#400]
## I'm submitting a...
* (X) Bug report *- please add **bug:** before the title*

### Teamcraft Link
https://ffxivteamcraft.com//list/Vw2qUH2VRUIepSdiScR8

## Current behavior
Dungeon drops icon links to: https://www.garlandtools.org/db/images/missing%20name.png instead of https://garlandtools.org/db/icons/instance/type/61802.png

## Expected behavior

Shows the dungeon icon.

**Comment by Supamiu** [comment]
![](https://i.imgur.com/y7iiDty.png)
