### ISSUE TITLE
bug: Registration not working in Firefox

### ISSUE THREAD

**Issue by SuperJugy** [Supamiu/ffxiv-teamcraft#405]
### Browser
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

Have you disabled script-/adblockers before submitting? Yes
### Teamcraft Link
Registration page

## Current behavior
Displaying the following error when trying to register:
![unknown](https://user-images.githubusercontent.com/678780/41197491-8a6047e4-6c2e-11e8-9af6-84d52b3bcf04.png)

## Expected behavior
Registration should work in all browsers.

## Steps to reproduce
1. Go to registration page
2. Enter details
3. ????
4. Profit!

**Comment by SuperJugy** [comment]
An FC member reported this issue.

**Comment by Supamiu** [comment]
This is most likely due to an unknown plugin/extension blocking the request, couldn't reproduce with Firefox 60.

**Comment by SuperJugy** [comment]
He registered through chrome and he then tried again in FF and appeared to had fixed itself. I guess you can close this issue.
