### ISSUE TITLE
feat: commission board

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#415]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing

Basically, the idea is to allow people to create a list and set it as a "crafting request".
Then, people willing to make money would jump to the requests section, pick a thing to craft, craft it, and deliver.

But this is not as easy as it seems, we need to answer these questions: 

1. What if I create a request, a craft takes it, but doesn't craft it?
2. What if I accept a request as crafter, I craft items, but the guy doesn't need it anymore?
3. Should we add a "delay" option for the requests? To tell people we need it in X days max.

The idea is also to have the best UX possible, so we'll need a nice user story for it.

Nice to have with this:

 - Chat system, to chat with the crafter.
 - Score system, like eBay does, to find out if the crafter is a good crafter or a bad one.
 - Achievements yay !
 - Realtime notifications for new requests or updates on your requests.

**Comment by Supamiu** [comment]
https://docs.google.com/document/d/18IAIpKTIl9ugXon0MX_0NG2Zv7fB-H6pl0A7XmfC4yI/edit

**Comment by MDlumia** [comment]
I have a add on idea to this. It relates to the system listed and free companys. Idea would be to have members go on to the site and then click a button to make a request to just other registered crafters in the FC. Maybe ping said crafters who could do said item. Also stats and leader boards for like most helpful ect. (most orders done, best ratings ect) I was reading your Google docs and thought that might be a great way to build on it

**Comment by Supamiu** [comment]
@MDlumia You mean the ability to do this but just for a FC? Could be a nice addition yea, but would it be included inside the main one? Apart from it? Maybe we would only need a FC report feature

**Comment by Phoosy** [comment]
Instead of building out your own chat system (with the implied logging/data requirements it carries), why not hook into the webhook/bot functionality of Discord and have it use notifications that way? I'd be hard pressed to find an FC that _doesn't_ use Discord and it can carry all of the weight for you?

Also, with the scoring system, you could tie a crafter to a Lodestone character entry and use that to attach a rating/score system to assist in identity management.

**Comment by Supamiu** [comment]
@Phoosy The thing is that people might not want to use discord to chat, so I guess the easiest way to solve that is by having our own chat, allowing people to give their discordId to the other one if they want to talk with them using discord.

**Comment by Supamiu** [comment]
done
