### ISSUE TITLE
feat: Item List Sort by Raeanya

### ISSUE THREAD

**Issue by JLShusterman** [Supamiu/ffxiv-teamcraft#424]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
Give option to sort items in a crafting list by the class that creates it.

## What is the use case for this feature?
I'd like to see, for example, all of the WVR crafts grouped together, then all of the CRP, and so on. So if I have a list of all of the new gear, I can make everything one class at a time, limiting how often I have to change classes.

**Comment by JLShusterman** [comment]
That’s it. Is that already a feature?

**Comment by Supamiu** [comment]
Yes it is 😄 follow the gif and you'll be able to use it on live version.
