### ISSUE TITLE
Bug: Unable to add recipes to list

### ISSUE THREAD

**Issue by Norinara** [Supamiu/ffxiv-teamcraft#43]
I am unable to add most level 70 2 star recipe to any list. Steppe Tea is the only one that currently works for me. Jellied Compote and Persimmon Leaf Sushi also cannot be added. I had nearly all of them added to different lists a few days ago but haven't been able to add them since. No notification appears when making an attempt. It will create an empty list when trying to make a new list with one.

Thanks,

**Comment by Norinara** [comment]
Problem persists on both PCs I've tried, as well as both Chrome and Edge.

**Comment by Supamiu** [comment]
First of all, sorry for the time I took to reply, I'm living on GMT+2 so I was kinda sleeping 😄 

I just tested and adding a Persimmon Leaf sushi worked like a charm, no error at all :/

Can you please try again after you made a Ctrl+F5? It'll invalidate the page cache so I can be sure that you have the latest version of the application (I added a header specifying no cache but some browsers seem to not care).

If the problem persists, please post a screenshot here with console opened (F12 on chrome).

**Comment by Norinara** [comment]
Oh no problem at all, sleep is good :smile: 
Good news is I was able to get them added from a pc at work. I won't be able to test the PC I was having an issue on but if its working here you are probably right and clearing the page cashe would probably fix it. Will post an update later.

Thanks,

**Comment by Norinara** [comment]
Miss click haha

**Comment by Norinara** [comment]
Update! Clearing the cache appears to have fixed the problem. Wish I could give you more info on how I cause the issue originally but hey, hard to complain when its working again.

Thanks,

**Comment by Supamiu** [comment]
It was probably an issue related to the recent Localization changes, I fixed it in 1.2.3 but you were probably still using an older build.
