### ISSUE TITLE
feat: Display multiple nodes in timer notification

### ISSUE THREAD

**Issue by nyanpasudo** [Supamiu/ffxiv-teamcraft#430]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
Display multiple nodes in desktop notification

## What is the use case for this feature?
If 2 or more nodes are up at the same time, only a single node will show up as a notification. Knowing what nodes have all popped is helpful

**Comment by Supamiu** [comment]
Oh, I disabled that to avoid spamming on notificactions, but if you think it would be useful, then i'll reactivate it 😄

**Comment by nyanpasudo** [comment]
Could possibly add user setting to set a limit to the # of nodes that appear in a single notification?

Are you just using the Windows Notification API or a combination of a custom notification UI with the windows notification?

Is each node alarm that pops simultaneously creating their own notification?

**Comment by Supamiu** [comment]
>Could possibly add user setting to set a limit to the # of nodes that appear in a single notification?

I believe the absolute maximum of simultaneous nodes spawning is 3, which isn't that big of a spam.

>Are you just using the Windows Notification API or a combination of a custom notification UI with the windows notification?

For the desktop app, yeah, see https://github.com/Supamiu/ffxiv-teamcraft/blob/master/main.js#L192-L196 for more details.

>Is each node alarm that pops simultaneously creating their own notification?
Yes, they do.
