### ISSUE TITLE
feat: gather/vendor-only/drop-only material display

### ISSUE THREAD

**Issue by BigMacTobi** [Supamiu/ffxiv-teamcraft#444]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
An extra List that displays all the basic materials that do not have to be crafted first.
Basically everything you can gather, only buy by a specific npc or only get dropped by monsters.
If it is a drop-item, is should tell the use where to find it since there is no way to find that out ingame.
Same for the purchase-ony stuff.
## What is the use case for this feature?
Players only have to look to that display and know what they have to farm.
Multiple lists show different quantities for that list exclusive and verly long lists lagg very much, so a list excluded farming display would be one possible solution for that issue.
Also adding a tick on/off list that lists all the crafting lists so one can choose what materials they want to know would bring perfect clarity to this.

**Comment by Supamiu** [comment]
The idea is to be able to see only gatherings, craftings, or such, accross multiple lists. To counter performance issues.

Not sure if this or fixing the perfs is better.
