### ISSUE TITLE
feat: improvement for the item search

### ISSUE THREAD

**Issue by BigMacTobi** [Supamiu/ffxiv-teamcraft#445]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
More filtering options for the item search.
For:
-different kinds of equipment
-non equipment
-different kinds of recipes (normal and special recipes)
## What is the use case for this feature?
Improvement search function and thus the user experience with TC.

**Comment by Supamiu** [comment]
Hi, thanks for the suggestion 👍 

Can you please add some example search you'd like to do with this? by either editing the issue or posting a new comment to it.

**Comment by BigMacTobi** [comment]
I basically said all there is to know for this idea XD
It should be possible to filter more precisely and exclude stuff that one does not want to find.
Filtering for main weapon/tool, headpiece, torso, hands, waist, legs, feet, secondary, secondary weapon (as shield or tools), earring, necklace, bracelet, ring (as intended in my different kinds of equipment statement)
Furniture, housing pieces etc.

Additionally, I have seen the filter function does not find more than 50 items even if there are more for the filtered range, that should be fixed
