### ISSUE TITLE
bug: tooltip in simulator is hidden indefinitely after dragging a skill

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#450]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
*currently not at home, will paste when I get home, but has been confirmed by other people already*

Have you disabled script-/adblockers before submitting?
yes

## Current behavior
This is an issue ever since #423 got fixed. Basically the first time you drag a skill the tooltip is deactivated, but after the drag ends it is not enabled again until a reload (or navigating away from the page).

## Expected behavior
Tooltips should be re-enabled after drag ends.

## Steps to reproduce
Here's a video because I'm lazy like that:
https://i.imgur.com/zYl2zjR.gifv

**Comment by rikai** [comment]
A small update to this:

Dragging another skill onto the bar from the selection area restores the ability to see tooltips again until the bar is rearranged again.

**Comment by mihawk90** [comment]
Hm, dragging another skill on the list doesn't do anything for me regarding tooltips :/
