### ISSUE TITLE
bug: titles on commission board list get fcked if too long

### ISSUE THREAD

**Issue by lanceangel** [Supamiu/ffxiv-teamcraft#451]
http://prntscr.com/k1f8z9

you need to limit characters in title
or
fix spacing in commission board list

**Comment by Supamiu** [comment]
Hello, thanks for the report.

Please consider using the template next time you log an issue, it makes it way easier to read for everyone.

**Comment by Supamiu** [comment]
fixed by https://github.com/Supamiu/ffxiv-teamcraft/commit/dc868d4d5867a22228dc3a52bdb9bc3f9559ec05
