### ISSUE TITLE
bug: both commission board ratings applied to single player

### ISSUE THREAD

**Issue by alexeiryn** [Supamiu/ffxiv-teamcraft#459]
## Environment
I'm not smart and have no idea what this means, sorry
### Browser
Mobile TC client
*Please state your browser and version. Go [here](https://ipchicken.com/) and copy everything after "Browser:".*

Have you disabled script-/adblockers before submitting?
### Teamcraft Link
https://ffxivteamcraft.com//list/yIokEGoXcP5lI9zragwB
### Layout code
If you're reporting a layout issue, please give us the layout code
```
Paste your Export code here
```

## Current behavior
I (Valtemont Solainteau/Alexeiryn) finished a commission on the board for Osrich Arkwright, and on finishing the commission, it popped up 4-5 "Rate player/confirm" windows (5 for him, 4-5 for me, I lost count exactly). Once we'd waded through those, it awarded me two 5-star ratings, and him 0.
![image](https://user-images.githubusercontent.com/40779912/42193995-59afdb3a-7e37-11e8-9949-a89bd68108f7.png)
## Expected behavior
It should have given us each one rating.
## Steps to reproduce
1. Create commission
2. Do commission
3. Rate Player

**Comment by Supamiu** [comment]
related to #462
