### ISSUE TITLE
feat: add Rowena collectable requirement to relevant timers (or notes feature)

### ISSUE THREAD

**Issue by alexeiryn** [Supamiu/ffxiv-teamcraft#460]
## What feature are you proposing
Add House of Splendors Collectability requirements to the Timers section. This could be accomplished either by baking it right in, or by simply adding an optional ability to add a custom User Note. I've done mock-ups for both ways below:
![image](https://user-images.githubusercontent.com/40779912/42239634-1d638cd8-7eca-11e8-867e-a17c4c275f8e.png)
In the case of baked-in, the Teleport/timer has been moved up slightly to accommodate the addition of right-alighed (for higher collectability) information below it. This is just the way I thought of, but if you have better ideas I'm certainly not married to the placement -- I'd just like the information be available to me without constantly looking elsewhere for it.

(I do have some preference for baked-in, but the user note option also adds the ability for people to put whatever else they want on the timer in future, e.g. if they're doing three commissions from the commission board, they could note which is for what/how much)
## What is the use case for this feature?
I've been leveling a third DoL recently through collectables, and it's getting really old having to constantly check the Timers tab in-game to verify what the collectability floor is. I was thinking of putting a post-it on my monitor, but since I already always have the timers window open, I figured I'd ask if it could be added to that instead.

**Comment by Supamiu** [comment]
I think notes feature will be made for that, because having these informations isn't possible for now.

See #431
