### ISSUE TITLE
feat: improve commissions board

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#462]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing

Improving commission board system, following these steps:

 - [x] maybe changed "Crafted by:" to "Fulfilled by:" something neutral
 - [x] have both parties confirm payment/completion? e.g. - when the list is completed and the client recieves the items, they mark the comm "complete", and when the person supplying receives the gil they can mark it "paid", and automatically archive it afterwards and prompt rating
 - [x] maybe if the comm price value field is left 0, default to the output being "Negotiable"?
 - [x] seems somehow i have badges and notifications for archived comms
(which i cant get rid of because i cant interact with it any longer)
 - [x] im also being prompted to rate a lot randomly

Source: Ashe Kahkol on discord.

**Comment by AcidAshe** [comment]
To add to 4: i also now have a badge on my "My requests" tab, even though it is empty.

6: Perhaps a badge on the TC icon on the taskbar?
7: option to turn off notifications/mute notifications pop up on desktop (i have been spammed so hard)


![image](https://user-images.githubusercontent.com/33726059/42270635-5d1f1998-7f4f-11e8-9949-d7fb616df511.png)
![image](https://user-images.githubusercontent.com/33726059/42270642-637121c4-7f4f-11e8-9247-588ec4d9eff8.png)

**Comment by Supamiu** [comment]
@AcidAshe a badge on the taskbar icon is a good idea, but it's not as simple as it seems, as it's basically another icon (yeah discord does that). If someone can create the same icon (png) as we have currently with a badge on it, I'll be happy to add it 😄

**Comment by Supamiu** [comment]
> have both parties confirm payment/completion? e.g. - when the list is completed and the client recieves the items, they mark the comm "complete", and when the person supplying receives the gil they can mark it "paid", and automatically archive it afterwards and prompt rating

About this, I think it's better to have the client only being able to close the commission, because it needs the list to be completed and the payments to be done.

Because the list can only be marked as complete by the crafter, the commission wont be marked as archived until the items are made and because it's archived by the client, it wont be archived until he/she gets the items. Also, refactoring that is quite a lot of work ^^"

**Comment by Supamiu** [comment]
>seems somehow i have badges and notifications for archived comms
(which i cant get rid of because i cant interact with it any longer)

You can still interact with archived commissions, the badge says that you need to open it and you'll be prompted for a rating, I'm adding a badge to the "open commission" button to show this clearly.
