### ISSUE TITLE
feat: Add button to give more options to add Rotations, Alarms, to folders

### ISSUE THREAD

**Issue by MDlumia** [Supamiu/ffxiv-teamcraft#464]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (X) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
 a button or drop down on rotations or alarms  to add/ change  them to a certain  folder, for the idea of devices where drag  and drop don't always work 
## What is the use case for this feature?
well there  is some devices where the current drag drop system doesn't always work, and i heard its good to at least have 2 ways to do a thing most of the times. that if one way acts up the other way will still work.  also it helps on the aspect of making Teamcrafts features available on the most amount of devices and setups.

**Comment by Supamiu** [comment]
I think the best way of giving the ability to change folder to every devices is to have touch drag and drop implemented, adding a button for that feels like it's way too much just for that.

**Comment by MDlumia** [comment]
Closeing per  drag and drop fixes. thanks miu
