### ISSUE TITLE
feat: Either add path system to "Items" panel, or allow added items to be included in other panels

### ISSUE THREAD

**Issue by the0s0ph1st** [Supamiu/ffxiv-teamcraft#467]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## Current behavior
If you add gathering items into a list, they will only show up in the "Items" panel, and therefore you cannot use the path-making system in the "Gatherings" panel which would have been very convenient if you are trying to finish off your gathering log.

## What feature are you proposing
It is either (1) add the path system to the "Items" panel (which apparently is easier according to Miu) or (2) allow added items in lists to be included in other panels.

## What is the use case for this feature?
As already mentioned, this can be used to complete gathering logs easier, as well as give someone a more systematic way of gathering things for profit.

**Comment by Supamiu** [comment]
Will be in 4.3.4 release 😄

**Comment by the0s0ph1st** [comment]
Thank you!
