### ISSUE TITLE
Add a different colored icon for gathering

### ISSUE THREAD

**Issue by fiaba** [Supamiu/ffxiv-teamcraft#47]
In game client, Mining and Quarrying, like Harvesting and Logging have a different color. Would be sweet if we can have this as well in our lists <3

**Comment by Supamiu** [comment]
I found this: https://ffxiv.gamerescape.com/wiki/Dictionary_of_Icons for the icons.

I have to investigate to know if I have enough data to find out what kinf of gathering a node is, but it seems like it can be done 👍

**Comment by Supamiu** [comment]
Alright, it can definetly be done ! will be in 1.3.0 for sure.
