### ISSUE TITLE
bug: UI style problems on small screens (below 960 px)

### ISSUE THREAD

**Issue by ascobolonline** [Supamiu/ffxiv-teamcraft#473]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
*Please state your browser and version. Go [here](https://ipchicken.com/) and copy everything after "Browser:" Tested on newest firefox and desktop app

## Current behavior
On small sized windows (below 960 pixel I guess) the style goes bit wrong on list views
1. Timed Nodes show the hover texts permanent
2. finished items are not green/blue backgrounded
3. icon for alarms panel is missing

![display_bugs_small_size](https://user-images.githubusercontent.com/3620177/42411120-ceb82514-81f6-11e8-9171-fbc58fd6cde7.png)

## Expected behavior
1. Timed Node texts only appear on hover
2. items that are finished/ready to craft are green/blue backgrounded
3. Icon for alarms panel in the bottom right corner

![display_bugs_bigger_size](https://user-images.githubusercontent.com/3620177/42411125-d7dc26a4-81f6-11e8-8d02-80abecc9f62e.png)
(info: the screenshot is made with a window minimal bigger than half screen, so around 1000pixel or so)

## Steps to reproduce
1. Open a list in browser/desktop app on version 4.3.4
2. resize window width to below 960 pixel

**Comment by Supamiu** [comment]
oh, this is because <960px is considered as mobile, where hover doesn't exist :/

I wonder if the best thing here is a fix or if it should stay as it is, as if we change this, mobile will be affected. Except if we create a new responsive state being the desktop - small - size.

**Comment by ascobolonline** [comment]
I think the hover text is not so important. Just recognized it while writing down the other two. The alarm panel button is nice to have. But mostly the missing color is the biggest „bug“. ;) You kinda get used to these colors hihi
