### ISSUE TITLE
feat: rating shown on profile

### ISSUE THREAD

**Issue by AcidAshe** [Supamiu/ffxiv-teamcraft#482]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing

The ability to see our own commission rating on our profile page. Also maybe the ability to see our contact's ratings on their contact panel?

## What is the use case for this feature?

Easy place to view your own rating/contact's ratings.

**Comment by Supamiu** [comment]
@mattantonelli wanna do this one?
