### ISSUE TITLE
feat: recipe choice on custom rotations

### ISSUE THREAD

**Issue by CostasAK** [Supamiu/ffxiv-teamcraft#495]
**Is your feature request related to a problem? Please describe.**
Many people create rotations from the rotation page, instead of the recipe page. This causes their rotations to be stuck in custom mode. 

**Describe the solution you'd like**
When choosing to make a custom rotation from the rotation page, make the custom stats optional, giving the user the option to just load an existing recipe and the simulator actually switching to that recipe (as though it were chosen from the recipe search).

**Describe alternatives you've considered**
When creating a custom rotation, the recipe configuration could show a dropdown for class and a dropdown for recipe. Below those, a checkbox for "custom recipe" and below that the existing input boxes for custom rotations.
Checking that checkbox disables the dropdowns and enables the input boxes.
Choosing a recipe and class from the dropdowns fills in the input boxes as they do now, but additionally pressing apply or a checkmark button would switch the simulator to non-custom mode. Pressing that button when custom recipe stats are input (the custom checkbox is checked), keeps the simulator in custom mode.

**Comment by Supamiu** [comment]
closed by https://github.com/Supamiu/ffxiv-teamcraft/commit/a7078d84138381b1eb83757ac2eab90ed68da6df
