### ISSUE TITLE
feat: Mark items complete from navigation pane

### ISSUE THREAD

**Issue by RobertCGouge** [Supamiu/ffxiv-teamcraft#510]
**Is your feature request related to a problem? Please describe.**
When having the optimized navigation pane open, it would be nice to be able to mark items collected.

**Describe the solution you'd like**
The same functionality that is avaiable in the list should be avaiable from the navigation pane.

**Describe alternatives you've considered**
It is really just a nice to have as when marking items complete, sometimes the list re-orders itself.

**Additional context**
N/A

**Comment by Supamiu** [comment]
The list reorders itself when you mark items?

This is probably an issue to report, due to some ordering methods.

Can you please post a gif of this bug?
