### ISSUE TITLE
bug: alarm notifications for deleted items

### ISSUE THREAD

**Issue by efreebairn** [Supamiu/ffxiv-teamcraft#514]
**Describe the bug**
I am receiving notifications for items I've deleted from my alarm list.

**To Reproduce**
1. Add an item to default group
2. Delete it from default group
3. Still receive windows notification for the item when the node pops

**Expected behavior**
I expect to only receive alarms for items that are in my default group and not silenced. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  desktop app
 - Version 4.3.8

**Additional context**
I've done a clean install and a restart for my computer, neither has helped.

**Comment by Supamiu** [comment]
Are the alarms still playing even after you reloaded the app? Are they poping at the right timing? This looks like an issue related to the web notifications API, but if you're using desktop app, then it's quite strange ^^".

**Comment by RobertCGouge** [comment]
Yes, I have noticed that sometimes even when reloading, the alarms are still triggering at the same time.  I would say about half the time reloading the app kills the alarm.  I have noticed a reboot will always fix the issue.

**Comment by efreebairn** [comment]
They do not play after I reload the app, and they are popping at the right times.  I can also reproduce this on the website.

**Comment by efreebairn** [comment]
I'm adding and removing from the item search. I also noticed that even when I've muted the alarms using the mute alarms checkbox, I still get the audio queue for the removed item - not the windows notification popup though.

**Comment by Supamiu** [comment]
Seems like it's the same issue as https://github.com/Supamiu/ffxiv-teamcraft/issues/499 (and I thought it was fixed ^^")
