### ISSUE TITLE
feat: garlandtools style gathering node notifications

### ISSUE THREAD

**Issue by RobPFarley** [Supamiu/ffxiv-teamcraft#525]
**Is your feature request related to a problem? Please describe.**
I believe the current implementation of the early notification sounds for a gathering node could be improved. At the moment the options are a notification at the time the node spawns (too late), or a number of Eorzean hours before node spawn (too early). I often get notified around 3 mins before the node spawns (1 Eorzean hour), then forget to go to the node at the time it actually spawns 3 mins later.

**Describe the solution you'd like**
I prefer garlandtools' implementation of the notifications, where you can set both an early warning notification and a spawn time notification, both of which can be set with a user defined number of seconds before spawning, IRL seconds rather than Eorzean

**Additional context**
![screen shot 2018-07-27 at 11 37 08](https://user-images.githubusercontent.com/17273366/43316520-7f431674-9191-11e8-8c9e-75b8ae5d226c.png)

**Comment by Supamiu** [comment]
Hi, thank you for your feature request 😄 

I'm not sure i get why you consider the notification at the time the node spawns as too late, I mean it rings right when the node spawns ingame, usually one second before.

This could be implemented for sure, I just want to clarify the reason why it could be considered sa too late.

**Comment by RobPFarley** [comment]
I find it too late as I'm usually flicking between gathering and crafting. The reason I prefer the garlandtools implementation is that I can be notified 90 seconds prior to the node spawning, which is enough notice for me to finish the current craft and get over to the node in time for it to spawn. If I only get notified at the time it spawns I usually end up in an "OH SHI-" moment, especially if multiple nodes spawn at the same time, as that results in me having less time to get between them all after finishing my craft before they despawn.

**Comment by Supamiu** [comment]
Ok, now I get it :) I'll see how this will be added, maybe just a 30 eorzean minutes option for the alarm, or a custom seconds one, but I'm not sure the second one is the best option.

**Comment by RobPFarley** [comment]
I think the second option would be better as it gives the user more control over when they get notified, and more options is always better! :)

**Comment by Supamiu** [comment]
5.0 will allow for 0.5 eorzean hour parameter for early alarms, I'll see if I can implement the real life seconds too, but I'm not sure I get the point since you can also just make it ring right when it spawns :) or a parameter to ring it twice maybe (like "ring again on spawn").
