### ISSUE TITLE
Bug: empty options part of the windows client desktop.

### ISSUE THREAD

**Issue by alink-tothepast** [Supamiu/ffxiv-teamcraft#541]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
When I open the options (where the update button should be along with some other options), I see a blank page (as shown on the screenshot below).

**To Reproduce**
1. Launch Windows Client (4.4)
2. Click on Options
3. See that the options part is empty

**Expected behavior**
The options section with all the options it should have (check update, change theme etc...).

**Screenshots**
<img width="1920" alt="bug-options-44" src="https://user-images.githubusercontent.com/1677426/43678193-ff68db3a-980e-11e8-802b-5bd8ed812e85.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10 April Update
 - Browser Firefox
 - Version 61.0.1

**Additional context**
Happened just after finishing to update to 4.4 (had never seen this on previous releases).

**Comment by Supamiu** [comment]
Will be fixed in 4.4.1, that will be deployed in a couple of hours.
