### ISSUE TITLE
feat: pricing mode tweak

### ISSUE THREAD

**Issue by AcidAshe** [Supamiu/ffxiv-teamcraft#543]
**Is your feature request related to a problem? Please describe.**

With new enhanced pricing mode, I noticed the automated min craft cost for pre-crafts overrides the vendor cost (if the item HAS a vendor cost).

**Describe the solution you'd like**

If possible, for the vendor cost to override the automated min craft cost? Example:
custom (if checked) > vendor (if applicable, if lower than min craft cost) > min craft cost (automated)

**Describe alternatives you've considered**

Manually entering vendor costs as custom prices.... yeah. XD

**Comment by Supamiu** [comment]
will be in 4.4.2
