### ISSUE TITLE
feat: copy button for earning category in pricing

### ISSUE THREAD

**Issue by AcidAshe** [Supamiu/ffxiv-teamcraft#545]
**Is your feature request related to a problem? Please describe.**

Nope.

**Describe the solution you'd like**

A copy button to copy the item name and prices (HQ pref, NQ as well if others find it applicable). Example format of copy output:

Total: 230,000gil
Crimson Cider: 6,000gil x10
Tofu Pancakes: 5,000gil x10
Grade 2 Infusion of Strength: 4,000gil x30

**Describe alternatives you've considered**

Just manually writing it out in Notepad/chat.

**Additional context**

Just helps in telling the client the prices you set for their order. Instead of typing it out to them this would provide an easy copy+paste option to send them or post as a price list.

**Comment by Supamiu** [comment]
Example output:

```
Total: 4,294,566gil

 Black Willow Armillae of Crafting: 410,000gil x1(HQ)
 Black Willow Necklace of Crafting: 444,444gil x1(HQ)
 Black Willow Ring of Crafting: 210,000gil x1(HQ)
 Silvergrace Earrings of Crafting: 345,678gil x1(HQ)
 Onishi Tekko: 470,000gil x1(HQ)
 Onishi Zori: 520,000gil x1(HQ)
 Onishi Dogi: 440,000gil x1(HQ)
 Onishi Kasa: 440,000gil x1(HQ)
 Onishi Momohiki: 570,000gil x1(HQ)
 Onishi Obi: 444,444gil x1(HQ)
```
