### ISSUE TITLE
feat: Easy check for Master Books in lists

### ISSUE THREAD

**Issue by cking** [Supamiu/ffxiv-teamcraft#555]
**Is your feature request related to a problem? Please describe.**
If you have a list you work on, some crafts and gathers need master books.
![](https://kura.is-pretty.sexy/22b046.png)
You have no easy way of checking the current status for them (or editing them)

**Describe the solution you'd like**
It would be awesome to get either a highlight if you have (or have not?) obtained the book, or the book hides for those lines. (In the example above, I'm only missing the book for two nodes).
Also it would be awesome to be able to easily check off the book while staying on the page.

**Describe alternatives you've considered**
- Clicking on the warning icon takes you to the profile page. In there you have to click the correct class and master book. Then you have to navigate back to the list.
- Check ingame if you can craft or gather the requested item(s) making you tab out of the application, searching the item in the log and tab out again

**Additional context**
The screenshot: https://kura.is-pretty.sexy/22b046.png

**Comment by cking** [comment]
Okay some unrelated stuff cleared up in a discussion. Still i like for an easy way to add (not remove) master books from the list pages. Or be able to open the dialog box for changing them from the list without breaking the list workflow by navigating to the profile view.

**Comment by Supamiu** [comment]
Closed by #576
