### ISSUE TITLE
Wrong ingredients for non-1:1 trades

### ISSUE THREAD

**Issue by ascobolonline** [Supamiu/ffxiv-teamcraft#559]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
No idea if that is a small bug, but if you add a non-crafted item to a list the costs (exchange items) are not 100% correct. If you click on the bag icon TC shows that you need resistance tokens (incase of augmented 350-gear), which is true, but you also need 7 Thavnairian Rain for the exchange.

**To Reproduce**
1. Add an item with non-1:1 trades to a list, like Augmented 350 gear
2. Check the trade payments for the item
3. See wrong payments (compare to garlandtools)

**Expected behavior**
Show the right amounts

**Additional context**
Comment from Miu on Discord: "That's a bug, and it's because trades are 1:1 for now, in terms of item types"

**Comment by Supamiu** [comment]
Closed by #576
