### ISSUE TITLE
bug: Gathering Items is missing items from the 4.2 folklore nodes

### ISSUE THREAD

**Issue by Questwizard** [Supamiu/ffxiv-teamcraft#564]
**Describe the bug**
The Gathering Items feature doesn't seem to know that any of the items or folklore gathering nodes added in patch 4.2 exist. I can't get any of them to show up in search results to be able to add alarms.

**To Reproduce**
1. Click on Gathering Items on the menu.
2. Type in the name of any 4.2 folklore node item, like Black Willow Log, Silvergrace Ore, Hawk's Eye, etc.
3. No search results show up.

**Expected behavior**
Expected to receive search results for the entered items and be able to add them as an alarm.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Desktop App
 - Version: 4.4.4

**Additional context**
These items show up and work properly on Garland Bell, so I'm not sure why it doesn't work here given that the data comes from Garland Tools.

**Comment by Supamiu** [comment]
Hello, thanks for the report.

To add an alarm, you should use the alarms page for now, as gathering items miught miss some of them. steps are:

1. Go to alarms page
2. Click the bell icon with a + in top-right corner
3. Search for the item.
4. Add alarm for this item using the button in front of the search result row.

I'm sorry for this bug and I'll do my best to remove it in 5.0 update that I'm currently working on.
