### ISSUE TITLE
bug: favorited list owned by different user doesn't show in favorites

### ISSUE THREAD

**Issue by efreebairn** [Supamiu/ffxiv-teamcraft#565]
**Describe the bug**
When I favorite a list that a friend is working on so I can help them, it does not show up in my favorites. It doesn't show in either the desktop app or on the website app. 

**To Reproduce**
1. Go to a friend's list.
2. Click on the heart icon to favorite it.
3. Go to favorites.
4. See nothing.

**Expected behavior**
I expect to see the list I favorited there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 4.4.4

**Additional context**

**Comment by Supamiu** [comment]
Hello, thank you for this bug report.

This will hopefully be fixed in 5.0 release that I'm working on 😄

**Comment by Supamiu** [comment]
Closed by #574
