### ISSUE TITLE
feat: Separate regular and high end crafts in the crafting milestones

### ISSUE THREAD

**Issue by KarstenS123** [Supamiu/ffxiv-teamcraft#566]
I did put up an entire set of crafts I wanted to do, collected all materials an came to the point to start crafting.

Then I saw the first craft in the list, eat my food and drunk my tea and started. After finishing the amount of crafts I went to the next ones in milestone 1. Alot of regular crafts I do not need food or tea for.

It would be nice if lower end crafts and high end crafts could be separated in milestones, beginning with the lower end crafts.

This would help to start using food and tea only when really needed.

**Comment by Supamiu** [comment]
Hello, sorry for the delay :/

if I understand this properly, you would like to sort crafts by difficulty? Because at the moment, crafter level and amount of stars are shown at the end of each row of the list, so I'm not sure I understand.

That being said, ordering by difficulty could really be a nice thing :) I'll check this for 5.0.

**Comment by KarstenS123** [comment]
Hello.

Sorry for the late answer.

Take a look into this list for example (I hope you can):

https://ffxivteamcraft.com/list/15pKkpBG8oCgMdE3tZ4c

There are 3 milestones for crafting.

In the first milestone 4 of 11 recipes are 4 star. The others are low end crafts.

In the second milestone 1 of 3 recipes is 4 star. The others are low end crafts, which even can be done without finishing the 4 star crafts of milestone 1.

The point of my question is: I do need food for crafting only for the 4 star recipes. Everything else can be done without. So I start with all low end crafts and then I take food and do the 4 start crafts.

So bringing the low end crafts into Milestones 1 and 2 and then the 4 star crafts as a separate thing with 3 milestones would make this alot easier for me than picking all low end crafts manually out of the list before I start with the 4 star crafts.

Greeting Karsten

Von: Flavien Normand [mailto:notifications@github.com]
Gesendet: Mittwoch, 12. September 2018 20:20
An: Supamiu/ffxiv-teamcraft <ffxiv-teamcraft@noreply.github.com>
Cc: KarstenS123 <Karsten.Schilder@live.de>; Author <author@noreply.github.com>
Betreff: Re: [Supamiu/ffxiv-teamcraft] feat: Separate regular and high end crafts in the crafting milestones (#566)


Hello, sorry for the delay :/

if I understand this properly, you would like to sort crafts by difficulty? Because at the moment, crafter level and amount of stars are shown at the end of each row of the list, so I'm not sure I understand.

That being said, ordering by difficulty could really be a nice thing :) I'll check this for 5.0.

**Comment by Supamiu** [comment]
This will be covered by v5 refactor as it now shows level next to the craft, easier for you to read which craft requires which level. You can also order by level inside the layout settings to complete that 😃
