### ISSUE TITLE
feat: tweaks to alarms overlay

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#568]
**Is your feature request related to a problem? Please describe.**
Not really a "problem", but some things are just not well visible in the alarms overlay, and I need to check the list every time the timer comes back around.

**Describe the solution you'd like**
So far 3 small things, and some optionals:

1. Make the slot-number better visible, there are some items where the name gets too long to be visible in the small-width overlay:
![image](https://user-images.githubusercontent.com/556162/45329885-e482cd00-b562-11e8-9e9d-7adf0be61fca.png)
2. Due to sometimes very similar icons on SE's part, it's not always clear whether the alarm is BTN or MIN, so an icon would be nice
3. Display the amount to collect - filled automatically when added from a list and/or manual override/set when added from alarms panel
4. optional: Remove an alarm from the overlay
5. optional: The attached note on an alarm

**Describe alternatives you've considered**
Consider the following work of art:
![image](https://user-images.githubusercontent.com/556162/45330172-6fb09280-b564-11e8-95ea-21c54568133d.png)
A: BTN/MIN Icon
B: The amount to collect (see also E)
C: Close button (only visible on hover?)
D: The note, with complete text in a hover-popup
E: The amount to collect, might be better here due to character restrictions in a small badge as in B
F: Moved slot number

B, D and E can be hidden when nothing was entered

**Comment by mihawk90** [comment]
Yeah that's what I meant. When adding it from a list it could add the amount, or people could fill it manually when added from anywhere else or to overwrite.

**Comment by mihawk90** [comment]
An icon for ephemeral nodes would be nice as well, since those can be made to respawn.

**Comment by Supamiu** [comment]
I applied the changes requested, just not the amount required because it's not possible just yet, sorry :/

Will be in 5.0.12
