### ISSUE TITLE
[5.0] Rework teams feature

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#573]
At the moment, teams are a bit hard to use, because member ids aren't shown, and their behavior is quite hard to figure out, here is a list of the features provided by teams so they can be reworked for 5.0:

- ~~Invite people from either userId or contacts.~~
- [x] Have a teams management page.
- [x] Ability to assign a list to a team (only for the leader)
- [x] Ability to assign an item to a team member (only for leader)

New possible features:

- [x] Discord hook for list updates ~~(patreon supporter teams only)~~
- [x] Short invite links (like discord ones) #548 
- ~~Invite using search character~~

**Comment by Makar8000** [comment]
May I suggest the ability to add members to a team by using their Character name / server? I have no idea what the userId or email is for my FC members.

**Comment by Supamiu** [comment]
Might be possible yeah, I'm going to add this as a feature to investigate, as it will depend on what I can do with the search system 😃
