### ISSUE TITLE
feat: Custom items

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#579]
After a talk with some hardcore & world prog crafters, the main issue with websites like Teamcraft at the moment is day 1 crafting. As the recipes and items become available only ~24h after the patch, which is way too late when you have to craft gear for a whole raid team during the first day.

To solve this, Teamcraft could implement custom items.

User would go to his custom items page, create a new one (with option to import from different format, using a given parser) and then he could add them to lists.

Custom items can have ingredients that are either items that are already known, or other custom items. They can also have informations on how to get them.

They also have to be exportable, for easy account transfer.

## Feature Checklist:

- [x] Custom items state, tied to current user.
- [x] Ability to add informations on how to get the item.
  - [x] Timed nodes support
  - [x] Ingredients support
  - [x] Trade/buy support
  - [x] Reduction support
- [x] Ability to import items from different formats.
   - [x] Flexible parser system, for an easy integration.
- [x] Ability to export items.
- [x] Ability to add custom items to lists.

**Comment by ayyaruq** [comment]
It's a bit obtuse but maybe being able to upload a slice of Item, Recipe, and RecipeLevelTable data at the very least from a Saint CSV export could be helpful. There's other tables needed to generate master book data and "crafted by job" data but those are the core to get names of items, materials, the min stats, and progress+quality. The format does change every so often but not every patch. Maybe allow users to map their own formats in the UI? The only downside I see is the time to actually do that is likely longer than just tracking in a spreadsheet or something.

**Comment by Supamiu** [comment]
Being able to map a custom format would take a lot of time imo, so yeah it would be longer than just use a sheet.

That being said, I can (or anybody, really) do a custom parser for each format, as the mapping can be done using a simple function.

I believe the saint CSV export will be one of the first parsers to be implemented 😄

**Comment by ayyaruq** [comment]
The format for that changes a bit every so often but the CSV headers don't always match it, when I get home I can link the 4.3 and maybe 4.4 column schemas.
