### ISSUE TITLE
bug: editing rotations moves them out of folders

### ISSUE THREAD

**Issue by SapozhnikovD** [Supamiu/ffxiv-teamcraft#589]
Desktop.

1) Create a rotation
2) Move it to a folder
3) Edit and save the rotation
4) It's not in the folder anymore

**Comment by Supamiu** [comment]
Hello, thank you for your report.

Do you think you can live with this bug? Because I'm currently working on 5.0 and I'm not sure this bug is worth the branch switch and configuration switch. As 5.0 wont have this bug anymore.
