### ISSUE TITLE
[5.0] Simulator rework

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#597]
List of inner features:

## Rotations listing page
  - [x] Share button to copy link
  - [x] Folders system with d&d for ordering
  - [x]  Button to rename rotation
  - [x] Share rotation folders

 ## Custom and regular simulator
- [x] Better accuracy !
- [x] Add an option for the +20/+20 stats on specialist tick, default to false
- [x] Don't add sound notification if macro is 15 steps long
- [x] Clone button
- [x] Share button in the simulator for current rotation
- [x] Save button (useless? Realtime Save?)
- [x] Reset button, to wipe the rotation
- [x] Import from crafting optimizer (ermad's simulator)
- [x] Import from ingame macro
- [x] Generate ingame macro
  - [x] The end sound should'nt be at the end of the craft
- [x] Maximum 10 cross-class skills
- [x] add Reclaim when cross-class slots are open
- [x] Minimum stats resolver
- [x] Step by step report
- [x] Screenshot-able display format (includes job, craftsmanship and control)
- [ ] Mobile-friendly display
- [x] Debug mode (snapshot at a given step)
- [x] Quick rotation switch button
- [x] Quick recipe change button
- [x] Custom stats system
- [x] Custom HQ ingredients, adds starting quality (display starting quality)
- [x] Consumables choice, food and tea (applies as edited)
  - [x] Button to save as default consumables
- [x] FC buffs choice, 2 at the same time max

**Comment by mihawk90** [comment]
* Maximum 10 cross-class skills
* add Reclaim when cross-class slots are open
