### ISSUE TITLE
feat: protect community lists from being filtered by some automatic criteria

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#600]
**Is your feature request related to a problem? Please describe.**
So ever since we got rid of a lot of - let's call them "low effort" - community lists there have been some unfortunate effects on legitimate lists that don't need rebuilding a lot of the time. An example would be a lot of the `Log` or `Leve` lists, they basically don't change ever and for that reason the owners usually will not regenerate them and so they will disappear at some point which is a shame.

**Describe the solution you'd like**
I think we would want some kind of system that protects certain lists from being filtered due to inactivity, currently I see 3 possibilities:
* manual selection by "moderators"
  * this does require a lot of effort and sifting through lists though
  * also there are no moderators
* upvotes/rating
  * currently there is no such thing (besides comments. which aren't a good indicator either)
  * I suspect this won't be easy to implement either. The issue with that is that most people will not go back to the community list selection just to upvote a list they have already cloned and finished.
  * As far as I know there is currently no connection between an "original" list and a "cloned" list, but if there was we could have a dialogue upon completion of a cloned list for "feedback" to the original list
  * this also goes with what I think I mentioned a while ago on discord, which would be public and private comments on list items - but I digress
* old items from older patches
  * old crafting items are very unlikely to change any time soon, so don't really need regenerating anyway
  * the patch data should(?) be in Garlands API

**Describe alternatives you've considered**
Initially when I thought about this I thought of using the tags, but that is not a good idea in my opinion. As soon as people realise certain tags exclude from inactivity we will start having the same issue we had initially as lists would just get tagged for exclusion, not for the actual tag

**Comment by Supamiu** [comment]
Closing as won't do, because community lists are managed differently now :)
