### ISSUE TITLE
[5.0] Desktop app improvements

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#602]
List of inner features:

 - [x] Custom protocol (https://glebbahmutov.com/blog/electron-app-with-custom-protocol/)
 - [ ] Larger scrollbar
 - [ ] Keep navigation upon app exit
 - [x] Remove old setups when installing new version

**Comment by ayyaruq** [comment]
Not to nitpick but basically all of #502, and probably some measure of #575 and enhancing profile view. Compare to say, Discord settings page and you'll see what I mean. I think the desktop app should really function like a desktop app, and not just a browser wrapper. I'm interested in working on this myself but probably can't do solo.
