### ISSUE TITLE
bug: "Add selection to a list" ignores number of selected items to craft

### ISSUE THREAD

**Issue by Webberjo** [Supamiu/ffxiv-teamcraft#603]
**Describe the bug**
Increasing the number of selected items you wish you craft and then clicking "Add selection to a list" only adds 1 of each item.

**To Reproduce**
1. Go to the Items page
2. Search for something (I searched for 'Rakshasa of Fending')
3. Check the checkbox next to an item (I checked the Necklace and Ring)
4. Increase the number to the right of a selected item to 2 (I increased Ring to 2)
5. Click "Add selection to a list" at the top of the page
6. Click "+ New List"
7. Enter a name for the list
8. Click "Confirm"

**Expected behavior**
The amount of selected items to craft should be added to the list. In my case, 1 necklace and **2** rings should be added to the list.

**Desktop (please complete the following information):**
 - OS: Windows 7 Home Premium (64-bit)
 - Browser: Google Chrome
 - Browser Version: 69.0.3497.100 (Official Build) (64-bit)
 - Teamcraft Version: 4.4.13

**Comment by AcidAshe** [comment]
I can second this. I just kept forgetting to make an issue! It would be nice if this were fixed. *cough* RINGS *cough*

**Comment by Supamiu** [comment]
Closed by #569 (listed inside the inner features ^^)
