### ISSUE TITLE
bug: favorite saved but not in list

### ISSUE THREAD

**Issue by Kyara85** [Supamiu/ffxiv-teamcraft#608]
**Describe the bug**
Add a list to your favorites and open favorite list view. The list view contains no items.

**To Reproduce**
1. Add a list to your favorites
2. open favorite list view
3. error: list is empty

**Expected behavior**
Add a list to your favorites and open favorite list view. The list view contains all items of my favorites.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 69.0.3497.100

**Comment by Supamiu** [comment]
Hello, thank you for the report.

I'm really sorry about this issue, it is due to a bad design decision I'm fixing in 5.0, please look forward to it ;) 

Related to #565, will be fixed by #574.

**Comment by Supamiu** [comment]
Fixed by 4.4.16, that should be released soon, just waiting for one last feature to happen (or not, idk yet)
