### ISSUE TITLE
Cannot remove 'Working on it' status

### ISSUE THREAD

**Issue by ClulessCreations** [Supamiu/ffxiv-teamcraft#619]
There is no way to remove a crafter from the 'working on it' status of a list item after it's set.
According to the Teamcraft Wiki - there should be a removal button next to the profile picture:

> Each item has an icon to show that you're working on it (), clicking on it will add your profil picture to the row to say to everybody that you're the one working on it.
> 
> Once you clicked, you can remove your picture by clicking the remove button next to it to update the list by removing you as the person in charge of this item. 

**To Reproduce**
1. Create a list with at least one item for creation and one material required.
2. With a logged in crafter, access the list and click the briefcase icon to set yourself as 'Working on it'.
3. Attempt to remove the 'working on it' status.

**Expected behavior**
A button is expected to appear near the profile picture of the crafter set to working on the item.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit Professional
 - Browser:  Chrome v69.0.3497.100   Internet Explorer v11.345.17134.0

![bugpic](https://user-images.githubusercontent.com/44177092/46973103-211b7a00-d075-11e8-8a4e-f015802f3340.jpg)

**Comment by Supamiu** [comment]
Hi, thank you for your report.

If I remember correctly, this button only shows when you hover the profile picture, in order to avoid having too much stuff to show. Have you tried hovering it?

**Comment by ClulessCreations** [comment]
I had not.

Went back on both Chrome and I.E. to test.  Hovering over the profile portrait for an extended period of time (over 10 seconds) does not produce any buttons on either browser - it does show the hover text "So-and-so is working on it" though, but no buttons.
