### ISSUE TITLE
feat: Manual item ordering on lists panel

### ISSUE THREAD

**Issue by AltanSipdrae** [Supamiu/ffxiv-teamcraft#621]
I'd need a way to keep my lists ordered in the way I created them when glitches shuffle them, for organisation's sake.

I thought of a (yet another) button next to each list, which would allow you to enter a drag and drop mode for the list for which you clicked on the button, allowing you to drag and drop items around to reorder them the way you'd like.

**Comment by Supamiu** [comment]
What if the order was depending on your currently selected layout instead of having to reorder manually?

Got this random thought today, figured it could be the best solution
