### ISSUE TITLE
feat: being able to select DoH and DoL as filter in search page

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#680]
**Is your feature request related to a problem? Please describe.**
Not being able to select DoH/DoL in the search page is a bummer because we have to select each job one by one, which is kidna boring.

**Describe the solution you'd like**
A way to select DoH or DoL in the filters, either inside the list or via a "shortcut" button.

**Comment by Hranz** [comment]
I'd like to add a suggestion for the feature. Similarly to suggested above, it would be nice to group gear on /search by "accessories" (belt,ear,neck,wrist,rings) and "left-side" (head,chest,legs,feet). If adding groupings as such it might also be nice to have groups for DoW and DoM.

**Comment by Supamiu** [comment]
Sadly, this will be possible but limited, so I'm not going to add some handmade filters to the existing ones. What I did instead is to allow multiple categories to be selected at the same time, so you can search for items using multiple categories that will match with a union.

The issue behind that is that categories are ingame UICategory data, and there's no such category as DoH or DoL, there's one category per main hand tool type and offhand tool, then one per piece of gear, and other misc categories.
