### ISSUE TITLE
bug: pricing mode incorrectly summing

### ISSUE THREAD

**Issue by efreebairn** [Supamiu/ffxiv-teamcraft#692]
## Environment
Windows desktop application
### Browser
N/A

## Current behavior
Only sums the first section of items - crystals. Everything else is ignored - clicking the checkbox by individual items doesn't change the expected earnings. Also, the toggle at the top for "expect to sell everything" doesn't do anything currently.

## Expected behavior
See changing numbers for the expected earnings as I check and uncheck the boxes for the different items.

## Steps to reproduce
1. Have a list, go to pricing mode
2. Fill in info for MB prices by clicking button to fetch from mogboard for each of the different sections
3. See bottom number and be puzzled that it doesn't represent any profit for making a profitable item

**Comment by efreebairn** [comment]
Did some more experimenting this morning - here's my test list if that's helpful: https://ffxivteamcraft.com/list/sq78fK0mp99c1O4P3ROg

I found several of distinct problems:
1) The earning is always 0 gil, no matter what boxes I check or uncheck
2) The spending number can change, but only if I select the precrafts that are directly used to make the final item. Checking or unchecking anything in the "Other" section does nothing, as does checking or unchecking the linseed oil (used to make varnish which is then used in the final product). Checking and unchecking crystals works as expected.
3) The "expect to sell everything" checkbox at the top of the list on the right does nothing that I can see, checking it and unchecking it had no effect.

**Comment by Supamiu** [comment]
Hi,

What is the version you're using for desktop app? I feel like some of the issues you encountered are alredy solved.

Also, the "expect to sell everything" button is very specific, it changes prices only if one of the precrafts yields too many items and you have some remaining, in this case, without this toggle, items will be priced as you craft them, meaning that the formula for the price will be `unit cost * amount crafted`, while it'll be `unit cost * amount of crafts * yield` if you expect to sell everything.

**Comment by efreebairn** [comment]
Thanks for clarifying the "expect to sell everything" button! I think I got confused by the UI - the only outstanding behavior that doesn't make sense to me now is that when I check the box by flax, the total price for everything goes UP rather than down, even though the price of the linseed oil and varnish both go down.

**Comment by efreebairn** [comment]
Also - I was using 5.0.3 for the desktop app.

**Comment by Supamiu** [comment]
I'm closing this as I made some changes to the pricing mode that should fix this.

If it doesn't, please feel free to reopen the issue so we can talk more about it 😄
