### ISSUE TITLE
feat: Double-click on List / Crafting Rotation to open them.

### ISSUE THREAD

**Issue by Nortfor** [Supamiu/ffxiv-teamcraft#700]
**Describe the solution you'd like**
Being able to double click on a list / crafting rotation or any feature to open it instead of using the button (if not available for web-version, maybe for the desktop app?)

**Describe alternatives you've considered**
None

**Additional context**
Just some more ease of access, as I still wish to click on a list to open them instead of using the Open List button on the right side.

**Comment by Supamiu** [comment]
Hey, thanks for the feature request :)

Where would you like this double click to be bound? On the panel header? On the tlist name?
