### ISSUE TITLE
bug: missing mining node in Mordona

### ISSUE THREAD

**Issue by efreebairn** [Supamiu/ffxiv-teamcraft#706]
**Describe the bug**
When I search for earth cluster in the alarms search, there is no unspoiled mining node (quarrying) in Mordona. This node shows up at 1-4pm, 5-8pm, 9-12pm.

**To Reproduce**
1. Go to alarms
2. Click on add new alarm
3. Search for earth cluster
4. See the botany node in mordona, and a bunch of other places where you can find earth clusters, but not the mining node in Mordona. 

**Expected behavior**
I expect to see the alarm for this mining node when I search for it for any elemental cluster (earth, fire, water, etc...)

**Desktop (please complete the following information):**
 - OS: Windows, version 5.0.10

**Comment by Supamiu** [comment]
Hey, thanks for the report

Indeed it seems like this node isn't in the database, mainly because we're getting them "by hand" and this one dodged the fetch it seems. I'll see with the databases we're using if we can add this one 😄
