### ISSUE TITLE
list Tab doesn't work on Destop App

### ISSUE THREAD

**Issue by Khuzvhan** [Supamiu/ffxiv-teamcraft#709]
![image](https://user-images.githubusercontent.com/14275181/51270982-7c7b4200-19ad-11e9-9cb3-ffd6bdd3aed8.png)

lists working fine on website, but the App has been like this for week now.

**Comment by Supamiu** [comment]
Hey, thanks for the report :)

Please update to latest desktop release, always available at https://ffxivteamcraft.com/desktop (redirects to latest github release).

Unfortunately, the auto updater is broken for now, you'll have to make desktop update by hand until I find a fix, could happen in 5.0.11 tho.

I usually release almost one update per day.

Please confirm that this fixes your issue with latest desktop app so I can close the issue 😄

**Comment by Khuzvhan** [comment]
it works! thanks for the quick response :) 
i got used to the auto-updates so i didn't even know about those recent releases T_T .
many thanks!

**Comment by Supamiu** [comment]
Yay, glad to see it's fixed now 👍 

I'm closing this issue as resolved.
