### ISSUE TITLE
bug: hide completed rows no longer stays checked if you leave/comeback to list

### ISSUE THREAD

**Issue by efreebairn** [Supamiu/ffxiv-teamcraft#715]
**Describe the bug**
Previously, when you clicked hide completed rows for a list, it would remember that preference and stay that way for all lists until you unchecked it. Now, every time I leave a list I have to recheck the box to make sure I can focus on the items I still need to finish. 

**To Reproduce**
1. Go to a list, check something off
2. Click "hide completed rows" at top of list
3. Go to any other page: search, alarms, etc...
4. Come back to list, see all the hidden items again

**Expected behavior**
I would expect that the choice to hide rows stays associated with the user and not the individual lists, in an easily accessible way for the user to change at will. That way folks that want to keep their finished items hidden can have that be their default way of seeing lists.

**Desktop (please complete the following information):**
 - OS: Windows 5.0.10

**Additional context**
I've tried experimenting with layouts a little to see if I can get the layout to accomplish what I'm looking for, but unfortunately it either gets overruled by the checkbox, or it ALWAYS hides the items, regardless of the checkbox. If you want more details I can provide my test layout codes.

**Comment by Supamiu** [comment]
I can make it so it's stored inside the localstorage, aka per platform :)

The layout hide toggle (the per-panel one) is combined with a logical OR, meaning that if you set the global hide to true, it'll apply on every panel (except the final one, items).
