### ISSUE TITLE
feat: show DoH/DoL levels on public profile

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#721]
The title speaks by itself ;) 

Could be nice to have the levels shown on public profile page, kinda like lodestone but only for DoH/DoL

**Comment by MDlumia** [comment]
i agree with this.  it would be quite nice

**Comment by Supamiu** [comment]
Closed by https://github.com/Supamiu/ffxiv-teamcraft/commit/9f8a35783c10ec4fd47d6fac24a8777634ce688e
