### ISSUE TITLE
feat: crafting log tracker

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#724]
**Is your feature request related to a problem? Please describe.**
At the moment, some users use very big lists for log tracking, this creates some serious performance issues and isn't very convenient to use.

**Describe the solution you'd like**
Having a log tracker that could:

- List recipes like ingame log does, per page
- Give you a way to check recipe as already done
- Help you to optimize gathering and everything for the log completion
- Have better performances than a complete list made for that

Nice to have:

- Auto updater using network parsing

**Comment by sharilton** [comment]
I think if possible, the log tracker should be like the user made lists, 1-5, 6-10, etc.  It should just be a list of items per tier, with options to create a quick list or add to a current list.  Each item should have an option to tick if it’s done, with maybe a toggle option to hide all completed items.

Maybe each tier should have an option to add all unticked items to a list (or a quick list) too. 

Maybe a warning that adding too much items to one list may make the list bugged, to avoid an issue of people adding 400 items to one list. 

I know this ones a little difficult but double crafts, the ones that require an item previously on the list.  I’m unsure how to approach to avoid it, it probably is unavoidable.

**Comment by Supamiu** [comment]
I think something that would be cool is to be able to know how much of a given item you need for the entire log. For instance, Natron is needed in a lot of crafts, of different levels. 

This is like next level but it would be interesting to know that somehow, even if idk how yet xD
