### ISSUE TITLE
feat: Select Multiple Item types in search filters.  

### ISSUE THREAD

**Issue by MDlumia** [Supamiu/ffxiv-teamcraft#728]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**
Yes, there  is times when one might get certain  commissions for diffrent items. Like Caster "armor" (Head,body,gloves, legs, feet) or Healer "accessories"  (necklace, Earring, bracelet, rings) or any combination.   
**Describe the solution you'd like**
the ability to  be able to select multiple item types in the search filters. for Search.  
**Describe alternatives you've considered**
there is the current option of just rembering which is what, or doing the item types one at a time, (and hoping you don't forget  where you were.)  (much longer process) 
**Additional context**
this would be super useful for things up coming with 5.0 and even now with BLU.  i was told that i might be a long term issue as it might need some collab with Clori and the GT Search  system, but all the same i think it would be a super addition to the suite

**Comment by Supamiu** [comment]
closed by https://github.com/Supamiu/ffxiv-teamcraft/commit/11f830a760a6557a37ac7a24eb35d9860f9ed812
