### ISSUE TITLE
feat: Chinese support for menu and items

### ISSUE THREAD

**Issue by gsmsh** [Supamiu/ffxiv-teamcraft#759]
I'm sorry that I didn't submit an issue before I submit a PR. My friend remind me that the usual process is to have a issue first.

**Describe the solution you'd like**
As discussed before, I can provide a zh-items.json which includes the Chinese items' names. When the user choose 'zh' as language, the LocalizedDataService could choose zh-items.json as data source. 

As for search function, I am still working on find a proper api for searching items with Chinese. Before I find a api, I plan to add a reminder in the menu localization, to tell the user to use english name for searching.

About the menu localization, I thought I can translate the "zh-CN.json", and then add the zh support on page

**Additional context**
I have finished the zh-items.json. If you need, I can provide it to you now, so that you can modify LocalizedDataService with it.

**Comment by Supamiu** [comment]
Haha no worries, I'm not very strict with process or anything :)

Thank you for the issue, it'll help a bit with tracking and I assigned it to you ^^

**Comment by Supamiu** [comment]
closed by #766
