### ISSUE TITLE
bug: favorited list doesn't show up on desktop app

### ISSUE THREAD

**Issue by efreebairn** [Supamiu/ffxiv-teamcraft#768]
**Describe the bug**
I have favorited a list from a friend using the web client (since I can't open teamcraft links in the desktop app). When I open the desktop app and go to my favorites, nothing is there. 

**To Reproduce**
1. Favorite a list on Chrome.
2. Open desktop app, go to favorites.
3. See no lists.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows, version 5.0.29
 - Browser: Chrome

**Additional context**
This is definitely a separate issue, but I really miss being able to open teamcraft links in the app.

**Comment by Supamiu** [comment]
Hello, thank you for the report, can you please tell me if you can see favorites inside the browser itself?

You should be able to open lists inside desktop app using the "open in desktop app" button, see the screenshot below.
![2019-02-18_13-57-25](https://user-images.githubusercontent.com/11519203/52952541-24a57180-3385-11e9-8dd8-bb4dd76ab55b.png)

**Comment by efreebairn** [comment]
I can see the list favorited in Chrome. Thanks for the screenshot for opening lists inside the desktop app. However, the icon is only available from the browser. Before, it was in the desktop app as well, so I could copy the link directly there without having the intermediate step of opening a browser window.
