### ISSUE TITLE
feat: tag list items

### ISSUE THREAD

**Issue by TiteiKo** [Supamiu/ffxiv-teamcraft#774]
In lists, I'd like to be able to tag lines with user-defined tags.

For example:

![image](https://user-images.githubusercontent.com/248372/53014295-60553f80-3448-11e9-8de5-8954683f00cd.png)

I'd tag the first item with "food", that way I can easily keep it for later and group thoses to avoid buff waste.

I took a simple example, but that would allow _(for people with no memory like me)_ to prepare which rotation to use on each line and organize crafting for huge lists.

An alternative could be a note on each line, but tags would allow for sorting/categorizing by them in a future feature.

**Comment by Supamiu** [comment]
So the idea would be to show some additional tags in the blank space between item name and input field if I understood properly?

While I think it could be nice indeed, I have some questions regarding this:

- How should we handle these when the item has alarms?
- Where should the tags be displayed on mobile?
- Should the tags be saved across lists? For instance, I tag item A as "food", then I create another list with the same item, should the tag still be here?
- You added some details about a possible "sort by tag" feature, can you please elaborate on that?

I could also use a bit more use cases, to understand the feature better 😄

**Comment by Supamiu** [comment]
Forgot to say it inside the comment itself, but feel free to join the discord server and DM me, I see that your UI is using french, which is also my native language, so we could probably talk about it easily using either DMs or direct call.

**Comment by MDlumia** [comment]
I completely approve of this Request. i would find it super useful as well.  like with my team as we often share rotations. i could leave a  Rotation short hand so people would know exactly what shared rotation i would use with that item, and to save me from my self from trying to make something late at night, and not using food to make it.
