### ISSUE TITLE
feat: customize buttons display in list details

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#782]
**Is your feature request related to a problem? Please describe.**
When using the list details page, users might want to access some features without having to open the "..." menu where all the features lie, but they need to be able to customize that, in order to have it displayed as they want.

**Describe the solution you'd like**
A way to customize what should be inside the "..." menu and what should just be displayed as-is.

**Additional context**
The main question here is do we want this to be inside the layout or just tied to the user account settings?

**Comment by TiteiKo** [comment]
IMHO it should be inside the layout:
I have a layout to prepare the list (mark what I need as HQ/NQ, retrieve from servants, buy, ...), where marking HQ/NQ and checking the prices would be nice to have directly. 
Another layout for gathering stuff, where those buttons are useless but the "I take care of that" one would be great to have.
And finally a layout for crafting where I use comments to note which rotation to use.
