### ISSUE TITLE
feat: todo list for gathered items

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#80]
The intent is to have a list of things to gather/buy, in order to prepare for a patch and/or fill your stocks without having to create a new list just to handle that, with recipes using the items you're looking for.

Here is the list of specs we have for the feature:

- Should be able to contain ingredients only.
- Can be shared.
- Multiple lists per user.
- Should have an amount (amount done needed or nah?).

**Comment by AltanRapsied** [comment]
Wouldn't it ruin the economy market if lists of mats to prepare for mass selling after a patch release were to be shared?
