### ISSUE TITLE
feat: add more ways to add custom rotations, etc to folders

### ISSUE THREAD

**Issue by MDlumia** [Supamiu/ffxiv-teamcraft#810]
**Is your feature request related to a problem? Please describe.**
The current drag and drop system doesn't exactly work appropriately at some times and it is hugely frustrating when one is trying to organize things like rotations, and such.  and for Rotations there is no other way but drag and drop.  

**Describe the solution you'd like**
I would like more ways to add things that are currently pure drag and drop. to have other possible ways to organize.  like Rotations  to a folder, like through the ,,, menu or other failsafes. 

**Describe alternatives you've considered**
no other ways i could think other then just currently suffering with the irksome nature of the drag and drop library and hoping it works more then it doesn't. 👎 

**Additional context**
Please help?

**Comment by Supamiu** [comment]
related to #796
