### ISSUE TITLE
Request: In-App updater

### ISSUE THREAD

**Issue by ArkfrostLumas** [Supamiu/ffxiv-teamcraft#813]
Heyho,

I know, this is just nitpicking, but as a QoL improvement I'd like to request in-app updates, instead of having to come here to GitHub and download a new installer-file and install it manually, every time a new update is released, especially since updates are so frequent on Teamcraft.

In my opinion this would be a great feature and I'd look forward to it, as soon as this is possible. It would already be an improvement, if in-app updates were at least possible for minor updates. For major updates, where completely new systems are introduced, I wouldn't have a problem with downloading a new installer though.

Best regards!

**Comment by mihawk90** [comment]
There is already an auto-updater, it just didn't work for a long time. Should be working after 5.1.

**Comment by Supamiu** [comment]
Hey, as mihawk90 said ebove, the auto updater is already something available since 5.1, the message that shows to tell you that you should download latest might be removed soon, as the auto updater is now working properly :)

**Comment by ArkfrostLumas** [comment]
Oh, I didn't know about that. Didn't use Teamcraft that much recently, but every time I did it had updates I had to download manually x)

But it's good, that there is an auto-updater :)
