### ISSUE TITLE
Timer bug

### ISSUE THREAD

**Issue by Brimcon** [Supamiu/ffxiv-teamcraft#86]
Upon using the timer in latest Chrome, even when not in a list the alert continues to play at various times. It is also not very clear when the timer is disabled or enabled.

**Comment by Supamiu** [comment]
About the fact that timers are randomly playing alerts sometimes, that's hard because it requires a lot of refactoring, which will happen right after 2.4.

I'm also interested in the "not very clear" part, what do you mean? Do you have any suggestions to fix that? 

Thanks for your report 👍

**Comment by Brimcon** [comment]
I guess initially it was rough to tell between if a timer was active or not, as the only difference was either a + sign or a Checkmark. Maybe changing the color of the icon (The clock in this case) or adding some sort of secondary notification may help.
I know that the button changes color to a very bright color to indicate that its active (Great for Color blind people) so I'm unsure of a good color for it.
Also, rebuilding the list seems to have stopped the alarms going off when disabled.

**Comment by Supamiu** [comment]
Fixed in 3.0.0-beta.0
