### ISSUE TITLE
bug: cannot enable discord integration for team

### ISSUE THREAD

**Issue by efreebairn** [Supamiu/ffxiv-teamcraft#862]
**Describe the bug**
When I go to the team management page (either in website browser or desktop app), and select [Enable Discord Updates], it takes me to a discord page. Then, I select the server I'd like to connect to, but when I go to select the channel, there are no options in the list. If I try to click the authorize button, it says in small text in red, "Please select a channel."

**To Reproduce**
1. Hover over character icon to enable drop down menu, click "Teams".
2. Create a new team.
3. Click on "Enable Discord Updates", which takes you to discord page (login required).
4. Select any server you have access to.
5. Click on select a channel - no options will appear. 

**Expected behavior**
I expect to be able to select the channel I would like teamcraft to update with messages.

**Screenshots**
![No Channel Bug](https://user-images.githubusercontent.com/9341714/56265445-6e1cef00-609e-11e9-9174-22de66a06c48.png)
![Error Message](https://user-images.githubusercontent.com/9341714/56265449-707f4900-609e-11e9-8c4b-bc20e23c81f1.png)

**Desktop (please complete the following information):**
 - OS: Windows, Desktop version 5.2.11

Bug also shows up in Chrome.

**Comment by Supamiu** [comment]
Hey, do you have permissions to manage bots and hooks on some channels inside this discord server?

**Comment by efreebairn** [comment]
I did have permissions, but I kept trying to use a server that didn't have different channels - oops! Sorry for the false alarm.
