### ISSUE TITLE
bug: Durium Sand provisioning mission missing

### ISSUE THREAD

**Issue by SanderLe** [Supamiu/ffxiv-teamcraft#865]
Durium Sand is missing from the list of level 70 Miner provisioning missions
Adding a picture of my Provisioning Missions as proof that it shows up at level 70
![image](https://user-images.githubusercontent.com/6931955/56319405-e39dc380-6161-11e9-85ce-35b5cc05bd5b.png)

**Comment by Supamiu** [comment]
closed by https://github.com/Supamiu/ffxiv-teamcraft/commit/af8c98a7471059279f3f735777aebe7152b57ee0
