### ISSUE TITLE
feat: Change the color of text or box to show when an item is ready to be made

### ISSUE THREAD

**Issue by ravenjolly** [Supamiu/ffxiv-teamcraft#92]
Garland tools for instance shows a blue filled bubble when you have all the prerequisite items to craft something.

 E.g. Molybdenum Ingot
requires two mats, when collected change the text color to blue or highlight the box blue or green or something

**Comment by Supamiu** [comment]
I spoke about this yesterday with some users on discord and it's definetly planned as I think it's a really nice feature to have 😄 

With #89 , this would be a really nice addition.

Will be implemented for 2.5 but I can't give you an ETA as refactoring has to be done first, so either 2.5 or 3.0, depending on how heavy the refactoring is.
