### ISSUE TITLE
Bug: Count mixup beween same Pre crafts and final items

### ISSUE THREAD

**Issue by Val870** [Supamiu/ffxiv-teamcraft#94]
Hi there ! 
While using this great website for aircraft craft, there was a case where same Pre crafts and final items count messed up a little. Here is the example: 

I have 24 Steel Ingots to do in Pre crafts (to do Steel Joint Plate later) and 24 **others** Steel Ingot in final items (because that's what it requires).
**All counters are at 0.** 
If I set 1 Steel Join as done, the Steel Ingots in the Pre crafts should increase as well (as it's with the Pre crafts items that we do the final ones). But it's the counter of the final Steel Ingots that increased. 

And the same report in French: 
J'ai 24 Lingot d'aciers dans les Crafts pré-requis (pour faire des Pattes en acier plus tard) et 24 **autres** Lingot d'aciers en tant qu'item final (parce que c'est ce que demande la liste d'items à rendre pour l'airship).
**Tous les comptes sont à 0.**
Si je rajoute 1 Patte en acier en tant qu'item fait, le compteur des Lingot d'aciers dans les Crafts pré-requis devrait augmenter aussi (comme c'est avec les Crafts pré-requis que l'on fait les items finaux). Or, c'est le compteur des Lingot d'aciers dans les Objects finaux qui a augmenté.

**Comment by Supamiu** [comment]
Will be fixed for 3.0, thank you for your report 👍 

This comes from the fact that both of these items have the same id, the method getting an item in a list gets them from their id and no more, so the first one is returned: the recipe.

**Comment by Supamiu** [comment]
Fixed by https://github.com/Supamiu/ffxiv-teamcraft/commit/8360918c436c2255aad7bbec4b812b88223c4365

Will be in 3.0.0-beta.4 (https://beta.ffxivteamcraft.com)
